# Training

In [5]:
!pip install datasets

Collecting datasets
  Downloading datasets-2.19.0-py3-none-any.whl (542 kB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 542.0/542.0 kB 7.1 MB/s eta 0:00:00
Requirement already satisfied: filelock in /usr/local/lib/python3.10/dist-packages (from datasets) (3.13.4)
Requirement already satisfied: numpy>=1.17 in /usr/local/lib/python3.10/dist-packages (from datasets) (1.25.2)
Requirement already satisfied: pyarrow>=12.0.0 in /usr/local/lib/python3.10/dist-packages (from datasets) (14.0.2)
Requirement already satisfied: pyarrow-hotfix in /usr/local/lib/python3.10/dist-packages (from datasets) (0.6)
Collecting dill<0.3.9,>=0.3.0 (from datasets)
  Downloading dill-0.3.8-py3-none-any.whl (116 kB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 116.3/116.3 kB 8.7 MB/s eta 0:00:00
Requirement already satisfied: pandas in /usr/local/lib/python3.10/dist-packages (from datasets) (2.0.3)
Requirement already satisfied: requests>=2.19.0 in /usr/local/lib/python3.10/dist-packages (from datasets) (2.31.0)
Requirement already satisfied: tqdm>=4.62.1 in /usr/local/lib/python3.10/dist-packages (from datasets) (4.66.2)
Collecting xxhash (from datasets)
  Downloading xxhash-3.4.1-cp310-cp310-manylinux_2_17_x86_64.manylinux2014_x86_64.whl (194 kB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 194.1/194.1 kB 11.5 MB/s eta 0:00:00
Collecting multiprocess (from datasets)
  Downloading multiprocess-0.70.16-py310-none-any.whl (134 kB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 134.8/134.8 kB 10.2 MB/s eta 0:00:00
Requirement already satisfied: fsspec[http]<=2024.3.1,>=2023.1.0 in /usr/local/lib/python3.10/dist-packages (from datasets) (2023.6.0)
Requirement already satisfied: aiohttp in /usr/local/lib/python3.10/dist-packages (from datasets) (3.9.5)
Collecting huggingface-hub>=0.21.2 (from datasets)
  Downloading huggingface_hub-0.22.2-py3-none-any.whl (388 kB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 388.9/388.9 kB 14.1 MB/s eta 0:00:00
Requirement already satisfied: packaging in /usr/local/lib/python3.10/dist-packages (from datasets) (24.0)
Requirement already satisfied: pyyaml>=5.1 in /usr/local/lib/python3.10/dist-packages (from datasets) (6.0.1)
Requirement already satisfied: aiosignal>=1.1.2 in /usr/local/lib/python3.10/dist-packages (from aiohttp->datasets) (1.3.1)
Requirement already satisfied: attrs>=17.3.0 in /usr/local/lib/python3.10/dist-packages (from aiohttp->datasets) (23.2.0)
Requirement already satisfied: frozenlist>=1.1.1 in /usr/local/lib/python3.10/dist-packages (from aiohttp->datasets) (1.4.1)
Requirement already satisfied: multidict<7.0,>=4.5 in /usr/local/lib/python3.10/dist-packages (from aiohttp->datasets) (6.0.5)
Requirement already satisfied: yarl<2.0,>=1.0 in /usr/local/lib/python3.10/dist-packages (from aiohttp->datasets) (1.9.4)
Requirement already satisfied: async-timeout<5.0,>=4.0 in /usr/local/lib/python3.10/dist-packages (from aiohttp->datasets) (4.0.3)
Requirement already satisfied: typing-extensions>=3.7.4.3 in /usr/local/lib/python3.10/dist-packages (from huggingface-hub>=0.21.2->datasets) (4.11.0)
Requirement already satisfied: charset-normalizer<4,>=2 in /usr/local/lib/python3.10/dist-packages (from requests>=2.19.0->datasets) (3.3.2)
Requirement already satisfied: idna<4,>=2.5 in /usr/local/lib/python3.10/dist-packages (from requests>=2.19.0->datasets) (3.7)
Requirement already satisfied: urllib3<3,>=1.21.1 in /usr/local/lib/python3.10/dist-packages (from requests>=2.19.0->datasets) (2.0.7)
Requirement already satisfied: certifi>=2017.4.17 in /usr/local/lib/python3.10/dist-packages (from requests>=2.19.0->datasets) (2024.2.2)
Requirement already satisfied: python-dateutil>=2.8.2 in /usr/local/lib/python3.10/dist-packages (from pandas->datasets) (2.8.2)
Requirement already satisfied: pytz>=2020.1 in /usr/local/lib/python3.10/dist-packages (from pandas->datasets) (2023.4)
Requirement already satisfied: tzdata>=2022.1 in /usr/local/lib/python3.10/dist-packages (from pandas->datasets) (2024.1)
Requirement already satisfied: six>=1.5 in /usr/local/lib/python3.10/dist-packages (from python-dateutil>=2.8.2->pandas->datasets) (1.16.0)
Installing collected packages: xxhash, dill, multiprocess, huggingface-hub, datasets
  Attempting uninstall: huggingface-hub
    Found existing installation: huggingface-hub 0.20.3
    Uninstalling huggingface-hub-0.20.3:
      Successfully uninstalled huggingface-hub-0.20.3
Successfully installed datasets-2.19.0 dill-0.3.8 huggingface-hub-0.22.2 multiprocess-0.70.16 xxhash-3.4.1

In [2]:
# !pip install accelerate -U

In [6]:
!pip install rouge_score

Collecting rouge_score
  Downloading rouge_score-0.1.2.tar.gz (17 kB)
  Preparing metadata (setup.py) ... done
Requirement already satisfied: absl-py in /usr/local/lib/python3.10/dist-packages (from rouge_score) (1.4.0)
Requirement already satisfied: nltk in /usr/local/lib/python3.10/dist-packages (from rouge_score) (3.8.1)
Requirement already satisfied: numpy in /usr/local/lib/python3.10/dist-packages (from rouge_score) (1.25.2)
Requirement already satisfied: six>=1.14.0 in /usr/local/lib/python3.10/dist-packages (from rouge_score) (1.16.0)
Requirement already satisfied: click in /usr/local/lib/python3.10/dist-packages (from nltk->rouge_score) (8.1.7)
Requirement already satisfied: joblib in /usr/local/lib/python3.10/dist-packages (from nltk->rouge_score) (1.4.0)
Requirement already satisfied: regex>=2021.8.3 in /usr/local/lib/python3.10/dist-packages (from nltk->rouge_score) (2023.12.25)
Requirement already satisfied: tqdm in /usr/local/lib/python3.10/dist-packages (from nltk->rouge_score) (4.66.2)
Building wheels for collected packages: rouge_score
  Building wheel for rouge_score (setup.py) ... done
  Created wheel for rouge_score: filename=rouge_score-0.1.2-py3-none-any.whl size=24933 sha256=308a65475be49844714ca0c721f15c434570307bab49318dbb5beb9b80e6ce69
  Stored in directory: /root/.cache/pip/wheels/5f/dd/89/461065a73be61a532ff8599a28e9beef17985c9e9c31e541b4
Successfully built rouge_score
Installing collected packages: rouge_score
Successfully installed rouge_score-0.1.2

In [1]:
from google.colab import drive
drive.mount('/content/drive/')

Mounted at /content/drive/

In [2]:
import pandas as pd
import torch
import re
path = "/content/drive/MyDrive/NLP_2024/Project/Data_after_cleaning_and_splits/"

dataset_train = pd.read_csv(path+'train_dataset_final.csv')
dataset_test = pd.read_csv(path+'test_dataset_final.csv')
dataset_val = pd.read_csv(path+'val_dataset_final.csv')
print(dataset_test.columns)
prompt = "\nThis is a hateful post on reddit. What does it imply?"
prompt2 = "You can use this explanation to figure out what the post is about but focus on the original post for generation: "

dataset_train = dataset_train[dataset_train['offensiveYN'] == 1]
dataset_test = dataset_test[dataset_test['offensiveYN'] == 1]
dataset_val = dataset_val[dataset_val['offensiveYN'] == 1]

train_dataset = dataset_train[['post', 'targetStereotype', 'rationale']]
test_dataset = dataset_test[['post', 'targetStereotype', 'rationale']]
val_dataset = dataset_val[['post', 'targetStereotype', 'rationale']]
print(train_dataset.columns)
print(len(train_dataset))
print(len(test_dataset))
print(len(val_dataset))
def remove_last_sentence(text):
    # Use regex to split the text into sentences
    sentences = re.split(r'(?<!\w\.\w.)(?<![A-Z][a-z]\.)(?<=\.|\?)\s', text)

    # Remove the last sentence if there are more than one sentence
    if len(sentences) > 1:
        return ' '.join(sentences[:-1])
    else:
        return text

# Apply the function to the specified column
train_dataset['rationale'] = train_dataset['rationale'].apply(remove_last_sentence)
test_dataset['rationale'] = test_dataset['rationale'].apply(remove_last_sentence)
val_dataset['rationale'] = val_dataset['rationale'].apply(remove_last_sentence)

print(train_dataset.head())

dataset_train = train_dataset
dataset_test = test_dataset
dataset_val = val_dataset

dataset_train['input'] = None
dataset_train['output'] = None

dataset_val['input'] = None
dataset_val['output'] = None

dataset_test['input'] = None
dataset_test['output'] = None
post_prompt2 = "Implication is:\n"


dataset_train.reset_index(drop=True, inplace=True)
dataset_val.reset_index(drop=True, inplace=True)
dataset_test.reset_index(drop=True, inplace=True)
# print(dataset_train)

def list2samples(example, dataset):
    # print(example)
    dataset.loc[example, 'input'] = dataset.loc[example, 'post'] + prompt + prompt2 + dataset.loc[example, 'rationale']
    dataset.loc[example, 'output'] = post_prompt2 + dataset.loc[example, 'targetStereotype']


for i in range(len(dataset_train)):
    # print(dataset_train.loc[i])
    list2samples(i, dataset_train)

for i in range(len(dataset_val)):
    # print(dataset_val.loc[i])
    list2samples(i, dataset_val)

for i in range(len(dataset_test)):
    # print(dataset_test.loc[i])
    list2samples(i, dataset_test)

print(dataset_train.loc[0])
print(dataset_test.loc[0])
print(dataset_val.loc[0])

Index(['Unnamed: 0', 'whoTarget', 'intentYN', 'sexYN', 'sexReason',
       'offensiveYN', 'annotatorGender', 'annotatorMinority', 'sexPhrase',
       'speakerMinorityYN', 'WorkerId', 'HITId', 'annotatorPolitics',
       'annotatorRace', 'annotatorAge', 'post', 'targetMinority',
       'targetCategory', 'targetStereotype', 'dataSource', 'rationale'],
      dtype='object')
Index(['post', 'targetStereotype', 'rationale'], dtype='object')
10974
1750
1620

<ipython-input-2-f68a33c71c62>:35: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  train_dataset['rationale'] = train_dataset['rationale'].apply(remove_last_sentence)
<ipython-input-2-f68a33c71c62>:36: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  test_dataset['rationale'] = test_dataset['rationale'].apply(remove_last_sentence)
<ipython-input-2-f68a33c71c62>:37: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  val_dataset['rationale'] = val_dataset['rationale'].apply(remove_last_sentence)
<ipython-input-2-f68a33c71c62>:45: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  dataset_train['input'] = None
<ipython-input-2-f68a33c71c62>:46: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  dataset_train['output'] = None
<ipython-input-2-f68a33c71c62>:48: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  dataset_val['input'] = None
<ipython-input-2-f68a33c71c62>:49: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  dataset_val['output'] = None
<ipython-input-2-f68a33c71c62>:51: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  dataset_test['input'] = None
<ipython-input-2-f68a33c71c62>:52: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  dataset_test['output'] = None

                                                post  \
1  RT @iBeZo: Stupid fucking nigger LeBron. You f...
2  I need a girl from Jamaica I can't fuck with t...
3                           Molly make bitches crazy
5  It's funny when u get a black female mad they ...
8  A guy claiming to be Republican called C-Span ...

                   targetStereotype  \
1                        all stupid
2             black women are basic
3          women can't handle drugs
5           black women are trashy.
8  conservatives hate black people.

                                           rationale
1  This post is hateful because it uses derogator...
2  This post is hateful because it displays a cle...
3  This post uses derogatory language and promote...
5  This post is hateful because it perpetuates ha...
8  This post displays a clear and direct use of h...
post                RT @iBeZo: Stupid fucking nigger LeBron. You f...
targetStereotype                                           all stupid
rationale           This post is hateful because it uses derogator...
input               RT @iBeZo: Stupid fucking nigger LeBron. You f...
output                                    Implication is:\nall stupid
Name: 0, dtype: object
post                When u hitting it from the back u gotta call h...
targetStereotype          sexually promiscuous women are called sluts
rationale           This post promotes the use of degrading langua...
input               When u hitting it from the back u gotta call h...
output              Implication is:\nsexually promiscuous women ar...
Name: 0, dtype: object
post                Every half-breed cop in America is trying to r...
targetStereotype                                           rape women
rationale           This post is hateful because it promotes harmf...
input               Every half-breed cop in America is trying to r...
output                                    Implication is:\nrape women
Name: 0, dtype: object

In [3]:
dataset_train.head()

,post,targetStereotype,rationale,input,output
0,RT @iBeZo: Stupid fucking nigger LeBron. You f...,all stupid,This post is hateful because it uses derogator...,RT @iBeZo: Stupid fucking nigger LeBron. You f...,Implication is:\nall stupid
1,I need a girl from Jamaica I can't fuck with t...,black women are basic,This post is hateful because it displays a cle...,I need a girl from Jamaica I can't fuck with t...,Implication is:\nblack women are basic
2,Molly make bitches crazy,women can't handle drugs,This post uses derogatory language and promote...,Molly make bitches crazy\nThis is a hateful po...,Implication is:\nwomen can't handle drugs
3,It's funny when u get a black female mad they ...,black women are trashy.,This post is hateful because it perpetuates ha...,It's funny when u get a black female mad they ...,Implication is:\nblack women are trashy.
4,A guy claiming to be Republican called C-Span ...,conservatives hate black people.,This post displays a clear and direct use of h...,A guy claiming to be Republican called C-Span ...,Implication is:\nconservatives hate black people.

In [7]:
import torch
# print(torch.cuda.is_initialized())
import numpy as np
# print(torch.cuda.is_initialized())
import datasets
# print(torch.cuda.is_initialized())

from transformers import (
    AutoModelForSeq2SeqLM,
    AutoTokenizer,
)
# print(torch.cuda.is_initialized())

from tabulate import tabulate
# print(torch.cuda.is_initialized())
import nltk
# print(torch.cuda.is_initialized())
from datetime import datetime
# print(torch.cuda.is_initialized())
# device = torch.device("cuda") if torch.cuda.is_available() else "cpu"
# print(device)
# device = "cpu"

device = torch.device("cuda:0") if torch.cuda.is_available() else "cpu"
print(device)

train_x_json = {
    "input": [],
    "output": []
}
val_x_json = {
    "input": [],
    "output": []
}

test_x_json = {
    "input": [],
    "output": []
}

for i in range(len(dataset_train)):
    train_x_json['input'].append(dataset_train.loc[i, "input"])
    train_x_json['output'].append(dataset_train.loc[i, "output"])

for i in range(len(dataset_val)):
    val_x_json['input'].append(dataset_val.loc[i, "input"])
    val_x_json['output'].append(dataset_val.loc[i, "output"])

for i in range(len(dataset_test)):
    test_x_json['input'].append(dataset_test.loc[i, "input"])
    test_x_json['output'].append(dataset_test.loc[i, "output"])

from datasets import Dataset
train_dataset = Dataset.from_dict(train_x_json)
val_dataset = Dataset.from_dict(val_x_json)
test_dataset = Dataset.from_dict(test_x_json)

language = "english"
# from accelerate import Accelerator
# accelerator = Accelerator(mixed_precision="fp16",gradient_accumulation_steps=1)
model_name = "google/flan-t5-small"
save_name = "flant5smallmodelonlyrationale"
# model = AutoModelForSeq2SeqLM.from_pretrained(model_name)
# model = accelerator.prepare(model)
tokenizer = AutoTokenizer.from_pretrained(model_name)
# tokenizer = accelerator.prepare(tokenizer)
# Set model parameters or use the default
# print(model.config)
# tokenization


encoder_max_length = 512
decoder_max_length = 256

def batch_tokenize_preprocess(batch, tokenizer, max_source_length, max_target_length):
    source, target = batch["input"], batch["output"]
    source_tokenized = tokenizer(
        source, padding="max_length", truncation=True, max_length=max_source_length
    )
    target_tokenized = tokenizer(
        target, padding="max_length", truncation=True, max_length=max_target_length
    )

    batch = {k: v for k, v in source_tokenized.items()}
    # Ignore padding in the loss
    batch["labels"] = [
        [-100 if token == tokenizer.pad_token_id else token for token in l]
        for l in target_tokenized["input_ids"]
    ]
    return batch


train_data = train_dataset.map(
    lambda batch: batch_tokenize_preprocess(
        batch, tokenizer, encoder_max_length, decoder_max_length
    ),
    batched=True,
    remove_columns=train_dataset.column_names,
)

validation_data = val_dataset.map(
    lambda batch: batch_tokenize_preprocess(
        batch, tokenizer, encoder_max_length, decoder_max_length
    ),
    batched=True,
    remove_columns=val_dataset.column_names,
)

test_data = test_dataset.map(
    lambda batch: batch_tokenize_preprocess(
        batch, tokenizer, encoder_max_length, decoder_max_length
    ),
    batched=True,
    remove_columns=test_dataset.column_names,
)

test_data.set_format(type="torch")
train_data.set_format(type="torch")
validation_data.set_format(type="torch")

cuda:0

/usr/local/lib/python3.10/dist-packages/huggingface_hub/utils/_token.py:89: UserWarning:
The secret `HF_TOKEN` does not exist in your Colab secrets.
To authenticate with the Hugging Face Hub, create a token in your settings tab (https://huggingface.co/settings/tokens), set it as secret in your Google Colab and restart your session.
You will be able to reuse this secret in all of your notebooks.
Please note that authentication is recommended but still optional to access public models or datasets.
  warnings.warn(

tokenizer_config.json:   0%|          | 0.00/2.54k [00:00<?, ?B/s]

spiece.model:   0%|          | 0.00/792k [00:00<?, ?B/s]

tokenizer.json:   0%|          | 0.00/2.42M [00:00<?, ?B/s]

special_tokens_map.json:   0%|          | 0.00/2.20k [00:00<?, ?B/s]

Map:   0%|          | 0/10974 [00:00<?, ? examples/s]

Map:   0%|          | 0/1620 [00:00<?, ? examples/s]

Map:   0%|          | 0/1750 [00:00<?, ? examples/s]

In [8]:
from torch.utils.data import DataLoader
save_name = "flant5smallmodelonlyrationale"
def create_dataloaders(train_batch_size=8, eval_batch_size=8):
    train_dataloader = DataLoader(train_data, shuffle=True, batch_size=train_batch_size)
    val_dataloader = DataLoader(validation_data, shuffle=False, batch_size=eval_batch_size)
    # test_dataloader= DataLoader(test_data, shuffle=False, batch_size=eval_batch_size)
    return train_dataloader, val_dataloader

hyperparameters = {
    "learning_rate": 0.0001,
    "num_epochs": 1000, # set to very high number
    "train_batch_size": 1, # Actual batch size will this x 8 (was 8 before but can cause OOM)
    "eval_batch_size": 1, # Actual batch size will this x 8 (was 32 before but can cause OOM)
    "seed": 42,
    "patience": 3, # early stopping
    "output_dir": "./Models/" + save_name + "/"
}

# Borrowed from https://github.com/huggingface/transformers/blob/master/examples/seq2seq/run_summarization.py
import nltk
nltk.download("punkt", quiet=True)

metric = datasets.load_metric("rouge")


def postprocess_text(preds, labels):
    preds = [pred.strip() for pred in preds]
    labels = [label.strip() for label in labels]

    # rougeLSum expects newline after each sentence
    preds = ["\n".join(nltk.sent_tokenize(pred)) for pred in preds]
    labels = ["\n".join(nltk.sent_tokenize(label)) for label in labels]

    return preds, labels


def compute_metrics(eval_preds):
    preds, labels = eval_preds
    if isinstance(preds, tuple):
        preds = preds[0]
    decoded_preds = tokenizer.batch_decode(preds, skip_special_tokens=True)
    # Replace -100 in the labels as we can't decode them.
    labels = np.where(labels != -100, labels, tokenizer.pad_token_id)
    decoded_labels = tokenizer.batch_decode(labels, skip_special_tokens=True)

    # Some simple post-processing
    decoded_preds, decoded_labels = postprocess_text(decoded_preds, decoded_labels)

    result = metric.compute(
        predictions=decoded_preds, references=decoded_labels, use_stemmer=True
    )
    # Extract a few results from ROUGE
    result = {key: value.mid.fmeasure * 100 for key, value in result.items()}

    prediction_lens = [
        np.count_nonzero(pred != tokenizer.pad_token_id) for pred in preds
    ]
    result["gen_len"] = np.mean(prediction_lens)
    result = {k: round(v, 4) for k, v in result.items()}
    return result

import torch
import numpy as np
import datasets

<ipython-input-8-e577852bda62>:23: FutureWarning: load_metric is deprecated and will be removed in the next major version of datasets. Use 'evaluate.load' instead, from the new library 🤗 Evaluate: https://huggingface.co/docs/evaluate
  metric = datasets.load_metric("rouge")
/usr/local/lib/python3.10/dist-packages/datasets/load.py:759: FutureWarning: The repository for rouge contains custom code which must be executed to correctly load the metric. You can inspect the repository content at https://raw.githubusercontent.com/huggingface/datasets/2.19.0/metrics/rouge/rouge.py
You can avoid this message in future by passing the argument `trust_remote_code=True`.
Passing `trust_remote_code=True` will be mandatory to load this metric from the next major release of `datasets`.
  warnings.warn(

Downloading builder script:   0%|          | 0.00/2.17k [00:00<?, ?B/s]

In [9]:
import accelerate

In [10]:
from transformers import (
    AutoModelForSeq2SeqLM,
    AutoTokenizer,
    Seq2SeqTrainingArguments,
    Seq2SeqTrainer,
    DataCollatorForSeq2Seq,
    AutoModelForCausalLM,
    TrainingArguments,
    Trainer
)

from tabulate import tabulate
import nltk
from datetime import datetime
device = torch.device("cuda") if torch.cuda.is_available() else "cpu"


model = AutoModelForSeq2SeqLM.from_pretrained(model_name).to(device)
# model = AutoModelForCausalLM.from_pretrained("gpt2").to(device)
# model = accelerator.prepare(model)
tokenizer = AutoTokenizer.from_pretrained(model_name)

# Borrowed from https://github.com/huggingface/transformers/blob/master/examples/seq2seq/run_summarization.py

nltk.download("punkt", quiet=True)

metric = datasets.load_metric("rouge")


def postprocess_text(preds, labels):
    preds = [pred.strip() for pred in preds]
    labels = [label.strip() for label in labels]

    # rougeLSum expects newline after each sentence
    preds = ["\n".join(nltk.sent_tokenize(pred)) for pred in preds]
    labels = ["\n".join(nltk.sent_tokenize(label)) for label in labels]

    return preds, labels


def compute_metrics(eval_preds):
    preds, labels = eval_preds
    if isinstance(preds, tuple):
        preds = preds[0]
    decoded_preds = tokenizer.batch_decode(preds, skip_special_tokens=True)
    # Replace -100 in the labels as we can't decode them.
    labels = np.where(labels != -100, labels, tokenizer.pad_token_id)
    decoded_labels = tokenizer.batch_decode(labels, skip_special_tokens=True)

    # Some simple post-processing
    decoded_preds, decoded_labels = postprocess_text(decoded_preds, decoded_labels)

    result = metric.compute(
        predictions=decoded_preds, references=decoded_labels, use_stemmer=True
    )
    # Extract a few results from ROUGE
    result = {key: value.mid.fmeasure * 100 for key, value in result.items()}

    prediction_lens = [
        np.count_nonzero(pred != tokenizer.pad_token_id) for pred in preds
    ]
    result["gen_len"] = np.mean(prediction_lens)
    result = {k: round(v, 4) for k, v in result.items()}
    return result

from transformers import DataCollatorForLanguageModeling

training_args = Seq2SeqTrainingArguments(
    output_dir="results",
    num_train_epochs=15,  # demo
    do_train=True,
    do_eval=True,
    per_device_train_batch_size=8,  # demo
    per_device_eval_batch_size=4,
    learning_rate=3e-05,
    warmup_steps=400,
    weight_decay=0.1,
    label_smoothing_factor=0.1,
    # predict_with_generate=True,
    logging_dir="logs",
    logging_steps=50,
    save_total_limit=3,
)

data_collator = DataCollatorForSeq2Seq(tokenizer, model=model)

trainer = Seq2SeqTrainer(
    model=model,
    args=training_args,
    data_collator=data_collator,
    train_dataset=train_data,
    eval_dataset=validation_data,
    tokenizer=tokenizer,
    compute_metrics=compute_metrics,
)

trainer.train()
print("Training Completed")
print("="*100)
trainer.save_model("./Models/" + save_name)
torch.cuda.empty_cache()
trainer.evaluate()
print("Evaluation completed")
print("="*100)


def generate_summary(test_samples, model):
    inputs = tokenizer(
        test_samples["inputSentence"],
        padding="max_length",
        truncation=True,
        max_length=encoder_max_length,
        return_tensors="pt",
    )
    input_ids = inputs.input_ids.to(model.device)
    # input_ids = inputs.input_ids
    attention_mask = inputs.attention_mask.to(model.device)
    # attention_mask = inputs.attention_mask
    outputs = model.generate(input_ids, attention_mask=attention_mask,max_new_tokens=1024)
    output_str = tokenizer.batch_decode(outputs, skip_special_tokens=True)
    return outputs, output_str


model_before_tuning = AutoModelForSeq2SeqLM.from_pretrained(model_name)
import time
test_samples = train_dataset[:10]
summaries_before_tuning = generate_summary(test_samples, model_before_tuning)[1]
start = time.time()
summaries_after_tuning = generate_summary(test_samples, model)[1]
end = time.time()
print(end-start)

test_samples = test_dataset.select(range(10))
for i in range(10):
    print("##########################################################################")
    print("Prompt")
    print(test_samples[i])
    print(test_samples[i]["inputSentence"])
    print("Expected")
    print(test_samples[i]["asisResponse"])
    # print("Before Fine Tuning:")
    # print(summaries_before_tuning[i])
    print("After Fine Tuning:")
    print(summaries_after_tuning[i])

config.json:   0%|          | 0.00/1.40k [00:00<?, ?B/s]

model.safetensors:   0%|          | 0.00/308M [00:00<?, ?B/s]

generation_config.json:   0%|          | 0.00/147 [00:00<?, ?B/s]

/usr/local/lib/python3.10/dist-packages/datasets/load.py:759: FutureWarning: The repository for rouge contains custom code which must be executed to correctly load the metric. You can inspect the repository content at https://raw.githubusercontent.com/huggingface/datasets/2.19.0/metrics/rouge/rouge.py
You can avoid this message in future by passing the argument `trust_remote_code=True`.
Passing `trust_remote_code=True` will be mandatory to load this metric from the next major release of `datasets`.
  warnings.warn(

Training Completed
====================================================================================================

OutOfMemoryError: CUDA out of memory. Tried to allocate 5.27 GiB. GPU 0 has a total capacity of 14.75 GiB of which 5.17 GiB is free. Process 21246 has 9.58 GiB memory in use. Of the allocated memory 6.32 GiB is allocated by PyTorch, and 3.13 GiB is reserved by PyTorch but unallocated. If reserved but unallocated memory is large try setting PYTORCH_CUDA_ALLOC_CONF=expandable_segments:True to avoid fragmentation.  See documentation for Memory Management  (https://pytorch.org/docs/stable/notes/cuda.html#environment-variables)

In [ ]:
import pickle

model_path = "/content/drive/MyDrive/NLP_2024/Project/Generation/flant5latest.pkl"

with open(model_path, 'wb') as f:
    pickle.dump(model, f)

In [11]:
print(model)

T5ForConditionalGeneration(
  (shared): Embedding(32128, 512)
  (encoder): T5Stack(
    (embed_tokens): Embedding(32128, 512)
    (block): ModuleList(
      (0): T5Block(
        (layer): ModuleList(
          (0): T5LayerSelfAttention(
            (SelfAttention): T5Attention(
              (q): Linear(in_features=512, out_features=384, bias=False)
              (k): Linear(in_features=512, out_features=384, bias=False)
              (v): Linear(in_features=512, out_features=384, bias=False)
              (o): Linear(in_features=384, out_features=512, bias=False)
              (relative_attention_bias): Embedding(32, 6)
            )
            (layer_norm): T5LayerNorm()
            (dropout): Dropout(p=0.1, inplace=False)
          )
          (1): T5LayerFF(
            (DenseReluDense): T5DenseGatedActDense(
              (wi_0): Linear(in_features=512, out_features=1024, bias=False)
              (wi_1): Linear(in_features=512, out_features=1024, bias=False)
              (wo): Linear(in_features=1024, out_features=512, bias=False)
              (dropout): Dropout(p=0.1, inplace=False)
              (act): NewGELUActivation()
            )
            (layer_norm): T5LayerNorm()
            (dropout): Dropout(p=0.1, inplace=False)
          )
        )
      )
      (1-7): 7 x T5Block(
        (layer): ModuleList(
          (0): T5LayerSelfAttention(
            (SelfAttention): T5Attention(
              (q): Linear(in_features=512, out_features=384, bias=False)
              (k): Linear(in_features=512, out_features=384, bias=False)
              (v): Linear(in_features=512, out_features=384, bias=False)
              (o): Linear(in_features=384, out_features=512, bias=False)
            )
            (layer_norm): T5LayerNorm()
            (dropout): Dropout(p=0.1, inplace=False)
          )
          (1): T5LayerFF(
            (DenseReluDense): T5DenseGatedActDense(
              (wi_0): Linear(in_features=512, out_features=1024, bias=False)
              (wi_1): Linear(in_features=512, out_features=1024, bias=False)
              (wo): Linear(in_features=1024, out_features=512, bias=False)
              (dropout): Dropout(p=0.1, inplace=False)
              (act): NewGELUActivation()
            )
            (layer_norm): T5LayerNorm()
            (dropout): Dropout(p=0.1, inplace=False)
          )
        )
      )
    )
    (final_layer_norm): T5LayerNorm()
    (dropout): Dropout(p=0.1, inplace=False)
  )
  (decoder): T5Stack(
    (embed_tokens): Embedding(32128, 512)
    (block): ModuleList(
      (0): T5Block(
        (layer): ModuleList(
          (0): T5LayerSelfAttention(
            (SelfAttention): T5Attention(
              (q): Linear(in_features=512, out_features=384, bias=False)
              (k): Linear(in_features=512, out_features=384, bias=False)
              (v): Linear(in_features=512, out_features=384, bias=False)
              (o): Linear(in_features=384, out_features=512, bias=False)
              (relative_attention_bias): Embedding(32, 6)
            )
            (layer_norm): T5LayerNorm()
            (dropout): Dropout(p=0.1, inplace=False)
          )
          (1): T5LayerCrossAttention(
            (EncDecAttention): T5Attention(
              (q): Linear(in_features=512, out_features=384, bias=False)
              (k): Linear(in_features=512, out_features=384, bias=False)
              (v): Linear(in_features=512, out_features=384, bias=False)
              (o): Linear(in_features=384, out_features=512, bias=False)
            )
            (layer_norm): T5LayerNorm()
            (dropout): Dropout(p=0.1, inplace=False)
          )
          (2): T5LayerFF(
            (DenseReluDense): T5DenseGatedActDense(
              (wi_0): Linear(in_features=512, out_features=1024, bias=False)
              (wi_1): Linear(in_features=512, out_features=1024, bias=False)
              (wo): Linear(in_features=1024, out_features=512, bias=False)
              (dropout): Dropout(p=0.1, inplace=False)
              (act): NewGELUActivation()
            )
            (layer_norm): T5LayerNorm()
            (dropout): Dropout(p=0.1, inplace=False)
          )
        )
      )
      (1-7): 7 x T5Block(
        (layer): ModuleList(
          (0): T5LayerSelfAttention(
            (SelfAttention): T5Attention(
              (q): Linear(in_features=512, out_features=384, bias=False)
              (k): Linear(in_features=512, out_features=384, bias=False)
              (v): Linear(in_features=512, out_features=384, bias=False)
              (o): Linear(in_features=384, out_features=512, bias=False)
            )
            (layer_norm): T5LayerNorm()
            (dropout): Dropout(p=0.1, inplace=False)
          )
          (1): T5LayerCrossAttention(
            (EncDecAttention): T5Attention(
              (q): Linear(in_features=512, out_features=384, bias=False)
              (k): Linear(in_features=512, out_features=384, bias=False)
              (v): Linear(in_features=512, out_features=384, bias=False)
              (o): Linear(in_features=384, out_features=512, bias=False)
            )
            (layer_norm): T5LayerNorm()
            (dropout): Dropout(p=0.1, inplace=False)
          )
          (2): T5LayerFF(
            (DenseReluDense): T5DenseGatedActDense(
              (wi_0): Linear(in_features=512, out_features=1024, bias=False)
              (wi_1): Linear(in_features=512, out_features=1024, bias=False)
              (wo): Linear(in_features=1024, out_features=512, bias=False)
              (dropout): Dropout(p=0.1, inplace=False)
              (act): NewGELUActivation()
            )
            (layer_norm): T5LayerNorm()
            (dropout): Dropout(p=0.1, inplace=False)
          )
        )
      )
    )
    (final_layer_norm): T5LayerNorm()
    (dropout): Dropout(p=0.1, inplace=False)
  )
  (lm_head): Linear(in_features=512, out_features=32128, bias=False)
)

In [12]:
from tqdm import tqdm

In [12]:
!pip install evaluate
!pip install bert_score

Collecting evaluate
  Downloading evaluate-0.4.1-py3-none-any.whl (84 kB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 84.1/84.1 kB 3.1 MB/s eta 0:00:00
Requirement already satisfied: datasets>=2.0.0 in /usr/local/lib/python3.10/dist-packages (from evaluate) (2.19.0)
Requirement already satisfied: numpy>=1.17 in /usr/local/lib/python3.10/dist-packages (from evaluate) (1.25.2)
Requirement already satisfied: dill in /usr/local/lib/python3.10/dist-packages (from evaluate) (0.3.8)
Requirement already satisfied: pandas in /usr/local/lib/python3.10/dist-packages (from evaluate) (2.0.3)
Requirement already satisfied: requests>=2.19.0 in /usr/local/lib/python3.10/dist-packages (from evaluate) (2.31.0)
Requirement already satisfied: tqdm>=4.62.1 in /usr/local/lib/python3.10/dist-packages (from evaluate) (4.66.2)
Requirement already satisfied: xxhash in /usr/local/lib/python3.10/dist-packages (from evaluate) (3.4.1)
Requirement already satisfied: multiprocess in /usr/local/lib/python3.10/dist-packages (from evaluate) (0.70.16)
Requirement already satisfied: fsspec[http]>=2021.05.0 in /usr/local/lib/python3.10/dist-packages (from evaluate) (2023.6.0)
Requirement already satisfied: huggingface-hub>=0.7.0 in /usr/local/lib/python3.10/dist-packages (from evaluate) (0.22.2)
Requirement already satisfied: packaging in /usr/local/lib/python3.10/dist-packages (from evaluate) (24.0)
Collecting responses<0.19 (from evaluate)
  Downloading responses-0.18.0-py3-none-any.whl (38 kB)
Requirement already satisfied: filelock in /usr/local/lib/python3.10/dist-packages (from datasets>=2.0.0->evaluate) (3.13.4)
Requirement already satisfied: pyarrow>=12.0.0 in /usr/local/lib/python3.10/dist-packages (from datasets>=2.0.0->evaluate) (14.0.2)
Requirement already satisfied: pyarrow-hotfix in /usr/local/lib/python3.10/dist-packages (from datasets>=2.0.0->evaluate) (0.6)
Requirement already satisfied: aiohttp in /usr/local/lib/python3.10/dist-packages (from datasets>=2.0.0->evaluate) (3.9.5)
Requirement already satisfied: pyyaml>=5.1 in /usr/local/lib/python3.10/dist-packages (from datasets>=2.0.0->evaluate) (6.0.1)
Requirement already satisfied: typing-extensions>=3.7.4.3 in /usr/local/lib/python3.10/dist-packages (from huggingface-hub>=0.7.0->evaluate) (4.11.0)
Requirement already satisfied: charset-normalizer<4,>=2 in /usr/local/lib/python3.10/dist-packages (from requests>=2.19.0->evaluate) (3.3.2)
Requirement already satisfied: idna<4,>=2.5 in /usr/local/lib/python3.10/dist-packages (from requests>=2.19.0->evaluate) (3.7)
Requirement already satisfied: urllib3<3,>=1.21.1 in /usr/local/lib/python3.10/dist-packages (from requests>=2.19.0->evaluate) (2.0.7)
Requirement already satisfied: certifi>=2017.4.17 in /usr/local/lib/python3.10/dist-packages (from requests>=2.19.0->evaluate) (2024.2.2)
Requirement already satisfied: python-dateutil>=2.8.2 in /usr/local/lib/python3.10/dist-packages (from pandas->evaluate) (2.8.2)
Requirement already satisfied: pytz>=2020.1 in /usr/local/lib/python3.10/dist-packages (from pandas->evaluate) (2023.4)
Requirement already satisfied: tzdata>=2022.1 in /usr/local/lib/python3.10/dist-packages (from pandas->evaluate) (2024.1)
Requirement already satisfied: aiosignal>=1.1.2 in /usr/local/lib/python3.10/dist-packages (from aiohttp->datasets>=2.0.0->evaluate) (1.3.1)
Requirement already satisfied: attrs>=17.3.0 in /usr/local/lib/python3.10/dist-packages (from aiohttp->datasets>=2.0.0->evaluate) (23.2.0)
Requirement already satisfied: frozenlist>=1.1.1 in /usr/local/lib/python3.10/dist-packages (from aiohttp->datasets>=2.0.0->evaluate) (1.4.1)
Requirement already satisfied: multidict<7.0,>=4.5 in /usr/local/lib/python3.10/dist-packages (from aiohttp->datasets>=2.0.0->evaluate) (6.0.5)
Requirement already satisfied: yarl<2.0,>=1.0 in /usr/local/lib/python3.10/dist-packages (from aiohttp->datasets>=2.0.0->evaluate) (1.9.4)
Requirement already satisfied: async-timeout<5.0,>=4.0 in /usr/local/lib/python3.10/dist-packages (from aiohttp->datasets>=2.0.0->evaluate) (4.0.3)
Requirement already satisfied: six>=1.5 in /usr/local/lib/python3.10/dist-packages (from python-dateutil>=2.8.2->pandas->evaluate) (1.16.0)
Installing collected packages: responses, evaluate
Successfully installed evaluate-0.4.1 responses-0.18.0
Collecting bert_score
  Downloading bert_score-0.3.13-py3-none-any.whl (61 kB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 61.1/61.1 kB 3.5 MB/s eta 0:00:00
Requirement already satisfied: torch>=1.0.0 in /usr/local/lib/python3.10/dist-packages (from bert_score) (2.2.1+cu121)
Requirement already satisfied: pandas>=1.0.1 in /usr/local/lib/python3.10/dist-packages (from bert_score) (2.0.3)
Requirement already satisfied: transformers>=3.0.0 in /usr/local/lib/python3.10/dist-packages (from bert_score) (4.40.0)
Requirement already satisfied: numpy in /usr/local/lib/python3.10/dist-packages (from bert_score) (1.25.2)
Requirement already satisfied: requests in /usr/local/lib/python3.10/dist-packages (from bert_score) (2.31.0)
Requirement already satisfied: tqdm>=4.31.1 in /usr/local/lib/python3.10/dist-packages (from bert_score) (4.66.2)
Requirement already satisfied: matplotlib in /usr/local/lib/python3.10/dist-packages (from bert_score) (3.7.1)
Requirement already satisfied: packaging>=20.9 in /usr/local/lib/python3.10/dist-packages (from bert_score) (24.0)
Requirement already satisfied: python-dateutil>=2.8.2 in /usr/local/lib/python3.10/dist-packages (from pandas>=1.0.1->bert_score) (2.8.2)
Requirement already satisfied: pytz>=2020.1 in /usr/local/lib/python3.10/dist-packages (from pandas>=1.0.1->bert_score) (2023.4)
Requirement already satisfied: tzdata>=2022.1 in /usr/local/lib/python3.10/dist-packages (from pandas>=1.0.1->bert_score) (2024.1)
Requirement already satisfied: filelock in /usr/local/lib/python3.10/dist-packages (from torch>=1.0.0->bert_score) (3.13.4)
Requirement already satisfied: typing-extensions>=4.8.0 in /usr/local/lib/python3.10/dist-packages (from torch>=1.0.0->bert_score) (4.11.0)
Requirement already satisfied: sympy in /usr/local/lib/python3.10/dist-packages (from torch>=1.0.0->bert_score) (1.12)
Requirement already satisfied: networkx in /usr/local/lib/python3.10/dist-packages (from torch>=1.0.0->bert_score) (3.3)
Requirement already satisfied: jinja2 in /usr/local/lib/python3.10/dist-packages (from torch>=1.0.0->bert_score) (3.1.3)
Requirement already satisfied: fsspec in /usr/local/lib/python3.10/dist-packages (from torch>=1.0.0->bert_score) (2023.6.0)
Collecting nvidia-cuda-nvrtc-cu12==12.1.105 (from torch>=1.0.0->bert_score)
  Using cached nvidia_cuda_nvrtc_cu12-12.1.105-py3-none-manylinux1_x86_64.whl (23.7 MB)
Collecting nvidia-cuda-runtime-cu12==12.1.105 (from torch>=1.0.0->bert_score)
  Using cached nvidia_cuda_runtime_cu12-12.1.105-py3-none-manylinux1_x86_64.whl (823 kB)
Collecting nvidia-cuda-cupti-cu12==12.1.105 (from torch>=1.0.0->bert_score)
  Using cached nvidia_cuda_cupti_cu12-12.1.105-py3-none-manylinux1_x86_64.whl (14.1 MB)
Collecting nvidia-cudnn-cu12==8.9.2.26 (from torch>=1.0.0->bert_score)
  Using cached nvidia_cudnn_cu12-8.9.2.26-py3-none-manylinux1_x86_64.whl (731.7 MB)
Collecting nvidia-cublas-cu12==12.1.3.1 (from torch>=1.0.0->bert_score)
  Using cached nvidia_cublas_cu12-12.1.3.1-py3-none-manylinux1_x86_64.whl (410.6 MB)
Collecting nvidia-cufft-cu12==11.0.2.54 (from torch>=1.0.0->bert_score)
  Using cached nvidia_cufft_cu12-11.0.2.54-py3-none-manylinux1_x86_64.whl (121.6 MB)
Collecting nvidia-curand-cu12==10.3.2.106 (from torch>=1.0.0->bert_score)
  Using cached nvidia_curand_cu12-10.3.2.106-py3-none-manylinux1_x86_64.whl (56.5 MB)
Collecting nvidia-cusolver-cu12==11.4.5.107 (from torch>=1.0.0->bert_score)
  Using cached nvidia_cusolver_cu12-11.4.5.107-py3-none-manylinux1_x86_64.whl (124.2 MB)
Collecting nvidia-cusparse-cu12==12.1.0.106 (from torch>=1.0.0->bert_score)
  Using cached nvidia_cusparse_cu12-12.1.0.106-py3-none-manylinux1_x86_64.whl (196.0 MB)
Collecting nvidia-nccl-cu12==2.19.3 (from torch>=1.0.0->bert_score)
  Using cached nvidia_nccl_cu12-2.19.3-py3-none-manylinux1_x86_64.whl (166.0 MB)
Collecting nvidia-nvtx-cu12==12.1.105 (from torch>=1.0.0->bert_score)
  Using cached nvidia_nvtx_cu12-12.1.105-py3-none-manylinux1_x86_64.whl (99 kB)
Requirement already satisfied: triton==2.2.0 in /usr/local/lib/python3.10/dist-packages (from torch>=1.0.0->bert_score) (2.2.0)
Collecting nvidia-nvjitlink-cu12 (from nvidia-cusolver-cu12==11.4.5.107->torch>=1.0.0->bert_score)
  Using cached nvidia_nvjitlink_cu12-12.4.127-py3-none-manylinux2014_x86_64.whl (21.1 MB)
Requirement already satisfied: huggingface-hub<1.0,>=0.19.3 in /usr/local/lib/python3.10/dist-packages (from transformers>=3.0.0->bert_score) (0.22.2)
Requirement already satisfied: pyyaml>=5.1 in /usr/local/lib/python3.10/dist-packages (from transformers>=3.0.0->bert_score) (6.0.1)
Requirement already satisfied: regex!=2019.12.17 in /usr/local/lib/python3.10/dist-packages (from transformers>=3.0.0->bert_score) (2023.12.25)
Requirement already satisfied: tokenizers<0.20,>=0.19 in /usr/local/lib/python3.10/dist-packages (from transformers>=3.0.0->bert_score) (0.19.1)
Requirement already satisfied: safetensors>=0.4.1 in /usr/local/lib/python3.10/dist-packages (from transformers>=3.0.0->bert_score) (0.4.3)
Requirement already satisfied: contourpy>=1.0.1 in /usr/local/lib/python3.10/dist-packages (from matplotlib->bert_score) (1.2.1)
Requirement already satisfied: cycler>=0.10 in /usr/local/lib/python3.10/dist-packages (from matplotlib->bert_score) (0.12.1)
Requirement already satisfied: fonttools>=4.22.0 in /usr/local/lib/python3.10/dist-packages (from matplotlib->bert_score) (4.51.0)
Requirement already satisfied: kiwisolver>=1.0.1 in /usr/local/lib/python3.10/dist-packages (from matplotlib->bert_score) (1.4.5)
Requirement already satisfied: pillow>=6.2.0 in /usr/local/lib/python3.10/dist-packages (from matplotlib->bert_score) (9.4.0)
Requirement already satisfied: pyparsing>=2.3.1 in /usr/local/lib/python3.10/dist-packages (from matplotlib->bert_score) (3.1.2)
Requirement already satisfied: charset-normalizer<4,>=2 in /usr/local/lib/python3.10/dist-packages (from requests->bert_score) (3.3.2)
Requirement already satisfied: idna<4,>=2.5 in /usr/local/lib/python3.10/dist-packages (from requests->bert_score) (3.7)
Requirement already satisfied: urllib3<3,>=1.21.1 in /usr/local/lib/python3.10/dist-packages (from requests->bert_score) (2.0.7)
Requirement already satisfied: certifi>=2017.4.17 in /usr/local/lib/python3.10/dist-packages (from requests->bert_score) (2024.2.2)
Requirement already satisfied: six>=1.5 in /usr/local/lib/python3.10/dist-packages (from python-dateutil>=2.8.2->pandas>=1.0.1->bert_score) (1.16.0)
Requirement already satisfied: MarkupSafe>=2.0 in /usr/local/lib/python3.10/dist-packages (from jinja2->torch>=1.0.0->bert_score) (2.1.5)
Requirement already satisfied: mpmath>=0.19 in /usr/local/lib/python3.10/dist-packages (from sympy->torch>=1.0.0->bert_score) (1.3.0)
Installing collected packages: nvidia-nvtx-cu12, nvidia-nvjitlink-cu12, nvidia-nccl-cu12, nvidia-curand-cu12, nvidia-cufft-cu12, nvidia-cuda-runtime-cu12, nvidia-cuda-nvrtc-cu12, nvidia-cuda-cupti-cu12, nvidia-cublas-cu12, nvidia-cusparse-cu12, nvidia-cudnn-cu12, nvidia-cusolver-cu12, bert_score
Successfully installed bert_score-0.3.13 nvidia-cublas-cu12-12.1.3.1 nvidia-cuda-cupti-cu12-12.1.105 nvidia-cuda-nvrtc-cu12-12.1.105 nvidia-cuda-runtime-cu12-12.1.105 nvidia-cudnn-cu12-8.9.2.26 nvidia-cufft-cu12-11.0.2.54 nvidia-curand-cu12-10.3.2.106 nvidia-cusolver-cu12-11.4.5.107 nvidia-cusparse-cu12-12.1.0.106 nvidia-nccl-cu12-2.19.3 nvidia-nvjitlink-cu12-12.4.127 nvidia-nvtx-cu12-12.1.105

In [8]:
test_dataset[0]

{'input': 'When u hitting it from the back u gotta call her "bitch" they love that but don\'t u dare call em "slut"\nThis is a hateful post on reddit. What does it imply?You can use this explanation to figure out what the post is about but focus on the original post for generation: This post promotes the use of degrading language towards women during sexual encounters. By encouraging the use of derogatory terms such as "bitch" and warning against using the term "slut", the author is perpetuating harmful and sexist attitudes towards women. This type of language reduces women to mere objects for male pleasure, rather than respecting them as equals. It also implies that women enjoy being disrespected and objectified during sex, perpetuating harmful stereotypes and promoting a culture of misogyny.',
 'output': 'Implication is:\nsexually promiscuous women are called sluts'}

In [16]:
import pickle

model_path = "/content/drive/MyDrive/NLP_2024/Project/Generation/flant5latest.pkl"

with open(model_path, 'wb') as f:
    pickle.dump(model, f)

#Load Model

In [9]:
import pickle

model_path = "/content/drive/MyDrive/NLP_2024/Project/Generation/flant5latest.pkl"

with open(model_path, 'rb') as f:
    modelloaded = pickle.load(f)

In [11]:
from tqdm import tqdm

In [15]:
test_targetsnew = []
test_generatednew = []
i = 0
for idx in tqdm(range(len(test_dataset))):
    inputs = str(test_dataset[idx]['input'])
    input_ids = tokenizer.encode(inputs, return_tensors="pt").to(device)
    output = modelloaded.generate(input_ids, max_length=50, num_beams=4, early_stopping=True)
    output_text = tokenizer.decode(output[0], skip_special_tokens=True)
    test_generatednew.append(output_text.split("Implication is:")[1].strip("\n").strip(" "))
    test_targetsnew.append(test_dataset[idx]['output'].split("Implication is:")[1].strip("\n").strip(" "))



import evaluate
rouge = evaluate.load('rouge')
results = rouge.compute(predictions=test_generatednew, references=test_targetsnew)
print(results)

from datasets import load_metric
metric = load_metric("rouge")
results = metric.compute(predictions=test_generatednew, references=test_targetsnew)
# print(results)
result = list(results.items())
for index in range(len(result)-1):
  type_, scores = result[index]
  precision = scores.mid.precision
  recall = scores.mid.recall
  f1 = scores.mid.fmeasure
  print(str(type_)+" with precision "+str(precision)+" with recall "+str(recall)+" and F1 score "+str(f1))

from bert_score import score as bert_score
Ptestft, Rtestft, F1testft = bert_score(cands=test_generatednew, refs=test_targetsnew, lang='en', verbose=True)
print("BERTScore Precision:", Ptestft.mean().item())
print("BERTScore Recall:", Rtestft.mean().item())
print("BERTScore F1:", F1testft.mean().item())

100%|██████████| 1750/1750 [05:41<00:00,  5.12it/s]

Downloading builder script:   0%|          | 0.00/6.27k [00:00<?, ?B/s]

{'rouge1': 0.32106604049545245, 'rouge2': 0.18183514263514255, 'rougeL': 0.3195949101318849, 'rougeLsum': 0.31972024567402746}

<ipython-input-15-52666f47339d>:20: FutureWarning: load_metric is deprecated and will be removed in the next major version of datasets. Use 'evaluate.load' instead, from the new library 🤗 Evaluate: https://huggingface.co/docs/evaluate
  metric = load_metric("rouge")
/usr/local/lib/python3.10/dist-packages/datasets/load.py:759: FutureWarning: The repository for rouge contains custom code which must be executed to correctly load the metric. You can inspect the repository content at https://raw.githubusercontent.com/huggingface/datasets/2.19.0/metrics/rouge/rouge.py
You can avoid this message in future by passing the argument `trust_remote_code=True`.
Passing `trust_remote_code=True` will be mandatory to load this metric from the next major release of `datasets`.
  warnings.warn(

Downloading builder script:   0%|          | 0.00/2.17k [00:00<?, ?B/s]

rouge1 with precision 0.3401206349206348 with recall 0.31750788226712556 and F1 score 0.32106604049545245
rouge2 with precision 0.18965238095238068 with recall 0.18216821908250463 and F1 score 0.18183514263514255
rougeL with precision 0.3378749433106577 with recall 0.31633039420896547 and F1 score 0.3195949101318849

tokenizer_config.json:   0%|          | 0.00/25.0 [00:00<?, ?B/s]

config.json:   0%|          | 0.00/482 [00:00<?, ?B/s]

vocab.json:   0%|          | 0.00/899k [00:00<?, ?B/s]

merges.txt:   0%|          | 0.00/456k [00:00<?, ?B/s]

tokenizer.json:   0%|          | 0.00/1.36M [00:00<?, ?B/s]

model.safetensors:   0%|          | 0.00/1.42G [00:00<?, ?B/s]

Some weights of RobertaModel were not initialized from the model checkpoint at roberta-large and are newly initialized: ['roberta.pooler.dense.bias', 'roberta.pooler.dense.weight']
You should probably TRAIN this model on a down-stream task to be able to use it for predictions and inference.

calculating scores...
computing bert embedding.

  0%|          | 0/28 [00:00<?, ?it/s]

computing greedy matching.

  0%|          | 0/28 [00:00<?, ?it/s]

done in 3.43 seconds, 510.88 sentences/sec
BERTScore Precision: 0.88962721824646
BERTScore Recall: 0.8917730450630188
BERTScore F1: 0.8905482888221741

In [ ]:
import pickle

model_path = "/content/drive/MyDrive/NLP_2024/Project/Generation/flant5latest.pkl"

with open(model_path, 'wb') as f:
    pickle.dump(model, f)

In [ ]:
import pickle

model_path = "flant5latest.pkl"

with open(model_path, 'wb') as f:
    pickle.dump(model, f)

In [ ]:
tokenised_targets = []

for entry in target_sentencesnew:
  new_entry = new_entry.strip("\n")
  tokenised_targets.extend(new_entry.split(" "))

tokenised_generated = []

for entry in generated_sentences:
  new_entry = new_entry.strip("\n")
  tokenised_generated.extend(new_entry.split(" "))

In [ ]:
new_tokenised_targets = []

for entry in tokenised_targets:
  if entry!="" and entry!=" ":
    new_tokenised_targets.append(entry)

new_tokenised_generated = []

for entry in tokenised_generated:
  if entry!="" and entry!=" ":
    new_tokenised_generated.append(entry)

In [ ]:
print(len(new_tokenised_targets))
print(len(new_tokenised_generated))

7713
6772

In [ ]:
print(new_tokenised_targets)

['sexually', 'promiscuous', 'women', 'are', 'called', 'sluts', 'women', 'are', 'self-centered/egotistical', 'black', 'people', 'are', 'crackheads', 'women', 'who', 'have', 'sex', 'before', 'marriage', 'are', 'ruined.', 'women', 'are', 'used', 'for', 'sex', 'nigga', 'is', 'a', 'slang', 'term', 'for', 'black', 'people', 'women', 'are', 'stupid', 'gay', 'men', 'should', 'be', 'called', 'fags', 'latinx', 'people', 'are', 'worthless.', 'are', 'niggers', 'calling', 'black', 'person', 'a', 'nigger', 'gays', 'are', 'bad', 'black', 'women', 'are', 'hoes', 'women', 'are', '"hoes"', 'women', 'love', 'to', 'complain', 'are', 'just', 'objects', 'women', 'are', 'sex', 'objects', 'black', 'people', 'are', 'criminals', 'women', 'are', 'whores', 'fat', 'people', 'think', "they're", 'smart', 'black', 'people', 'just', 'care', 'about', 'sex', 'faggot', 'is', 'a', 'derogatory', 'term', 'for', 'gay', 'people.', 'women', 'think', 'they', 'know', 'men', 'women', 'are', 'objects', 'slur', 'gay', 'men', 'like', 'chick', 'flicks', 'black', 'women', 'have', 'bad', 'hair', 'black', 'folks', 'talk', 'a', 'lot', 'women', 'are', 'objects', 'women', 'are', 'foul', 'black', 'people', 'deserve', 'to', 'be', 'called', 'names', 'are', 'just', 'objects', 'women', 'are', 'sex', 'objects', 'uses', 'the', 'n', 'word', 'gay', 'people', "don't", 'have', 'kids', 'fat', 'women', 'are', 'ugly', 'are', 'just', 'objects', 'women', 'are', 'bitches', 'women', 'are', 'promiscuous', 'women', 'are', 'refereed', 'to', 'as', 'a', 'derogatory', 'word', 'women', 'are', 'all', 'cheaters', 'being', 'fat', 'is', 'bad', 'women', 'are', 'promiscuous', 'women', 'are', 'sex', 'objects', 'women', 'are', '"hoes"', 'black', 'folks', 'are', 'poor', 'fat', 'people', 'are', 'disgusting', 'should', 'be', 'made', 'fun', 'of', 'women', 'are', 'hoes', 'women', 'sleep', 'with', 'a', 'lot', 'of', 'different', 'men', 'marginalized', 'their', 'illness', 'women', "can't", 'be', 'trusted', 'women', 'use', 'men', 'for', 'favors', 'women', 'are', 'promiscuous', 'women', 'exist', 'to', 'please', 'men', 'black', 'people', 'are', 'niggers', 'muslims', 'are', 'bad', 'people', 'women', 'are', 'bitches', 'gay', 'men', "don't", 'deserve', 'rights', 'act', 'like', 'tramps', 'effeminate', 'men', 'are', 'women', 'black', 'people', 'are', 'the', 'n', 'word', 'women', 'are', 'bitches', 'women', 'exist', 'to', 'please', 'men', 'are', 'all', 'hoes', 'women', 'are', 'bitches', 'mentally', 'disabled', 'people', 'are', 'not', 'smart', 'are', 'all', 'hoes', 'women', 'are', 'hoes', 'blacks', 'like', 'fried', 'chicken', 'are', 'just', 'objects', 'women', 'are', 'objects', 'black', 'people', 'are', 'niggas', 'women', 'are', 'sexually', 'promiscuous', 'women', 'are', 'lazy', 'women', 'are', 'hoes', 'women', 'are', 'hoes', 'black', 'people', 'are', 'niggahs', 'are', 'all', 'bitches', 'jews', 'are', 'ashamed', 'of', 'being', 'jewish', 'or', 'self', 'hating', 'liberals', 'are', 'predictable', 'all', 'white', 'people', 'have', 'potential', 'to', 'be', 'racist', 'gay', 'men', 'only', 'do', 'anal.', 'trivializes', 'harm', 'to', 'victims', 'gay', 'men', 'are', 'indecisive', 'gay', 'men', 'are', 'ugly', 'women', "don't", 'value', 'the', 'right', 'things', 'women', 'are', 'promiscuous', 'fat', 'women', 'are', 'unattractive', 'are', 'all', 'bitches', 'act', 'like', 'children', 'women', 'are', 'hoes', 'woman', 'are', 'sex', 'objects', 'women', 'are', 'attracted', 'to', 'money', 'women', 'are', 'more', 'likely', 'to', 'be', 'into', 'drugs.', 'women', 'are', 'all', 'the', 'same', 'mentally', 'disabled', 'folks', 'are', 'r*tarded', 'being', 'gay', 'is', 'wrong', 'women', 'are', 'bitches', 'mentally', 'disabled', 'folks', 'are', 'r*tarded', 'women', 'sleep', 'around', 'women', 'are', 'gold', 'diggers', 'women', 'are', 'promiscuous', 'women', 'are', 'hoes', 'women', 'are', 'bitches', 'should', 'die', 'fat', 'people', 'are', 'unattractive.', 'protect', 'illegals', 'liberals', 'are', 'annoying.', 'black', 'people', 'are', 'a', 'lesser', 'race', 'retarded', 'people', 'are', 'stupid', 'arabs', 'are', 'barbaric', 'black', 'people', 'are', 'ugly', 'derogatory', 'term', 'used', 'all', 'latinos', 'are', 'immigrants', 'black', 'people', 'are', 'niggers', 'are', 'sexually', 'promiscous', 'when', 'drunk', 'colombians', 'are', 'worthless', 'christians', 'take', 'advantage', 'of', 'tax', 'breaks', 'are', 'all', 'dumb', 'black', 'folks', 'are', 'dirty', 'are', 'niggers', 'black', 'folks', 'are', 'angry', 'women', 'are', 'bitches', 'is', 'inherently', 'bad', 'woman', 'are', 'bitches/female', 'dogs', 'disabled', 'people', 'are', 'worth', 'name', 'calling', 'womens', 'cheat', 'retarded', 'is', 'an', 'offensive', 'term', 'black', 'people', 'are', 'dishonest', 'women', 'are', 'hoes', 'conservatives', 'blindly', 'support', 'their', 'reps', 'women', 'are', 'childish', 'cops', 'are', 'racist', 'labour', 'party', 'folks', 'are', 'liars', 'trivializes', 'harm', 'to', 'victims', 'conservatives', 'are', 'perverts', 'uk', 'is', 'undesirable', 'are', 'hoes', 'black', 'people', "aren't", 'as', 'good', 'as', 'whites', 'women', 'who', 'enjoy', 'sex', 'are', 'whores.', 'women', 'being', 'assertive', 'are', 'bitchy', 'black', 'folks', "shouldn't", 'be', 'trusted', 'blacks', 'are', 'stupid', 'niggas', 'is', 'a', 'slang', 'term', 'niggas', 'is', 'a', 'slang', 'term', 'black', 'folks', 'are', 'disloyal', 'black', 'men', "don't", 'take', 'care', 'of', 'their', 'babies', 'are', 'idiots', 'uses', 'the', 'n', 'word', 'soviets', 'are', 'criminals', 'refers', 'to', 'women', 'as', 'bitches', 'men', 'only', 'drink.', 'are', 'failures', 'black', 'folks', 'are', 'inferior', 'women', 'act', 'like', 'they', 'are', 'superior', 'conservatives', 'are', 'incompetent', 'women', 'are', 'bitches', 'are', 'loose', 'black', 'folks', 'are', 'hateful', 'women', 'change', 'who', 'they', 'are', 'to', 'please', 'men', 'white', 'people', "aren't", 'superior', 'black', 'people', 'are', 'worthless', 'women', 'are', 'vindictive', 'trump', 'supporters', 'are', 'stupid', 'russians', 'are', 'always', 'doing', 'something', 'lesbian', 'women', 'are', 'lustful', 'pagans', 'are', 'less', 'than', 'christians', 'women', "aren't", 'equal', 'to', 'men', 'muslims', 'immigrants', 'are', 'terrorists', 'are', 'promiscous', 'making', 'our', 'democracy', 'less', 'than', 'women', 'are', 'refereed', 'to', 'as', 'a', 'derogatory', 'word', 'conservatives', 'are', 'spineless', 'korean', 'people', 'would', 'do', 'anything', 'to', 'get', 'what', 'they', 'want', 'mentally', 'disabled', 'folks', 'are', 'violent', 'makes', 'light', 'about', 'holocaust', 'afghans', 'practise', 'beastiality', 'priests', 'are', 'pedophiles', 'jews', 'should', 'be', 'burned', 'black', 'folks', 'are', 'like', 'animals', 'black', 'people', 'are', 'lynched.', 'implies', 'black', 'kids', 'are', 'fast', 'jewish', 'people', 'think', 'genocide', 'is', 'funny', 'black', 'people', 'are', 'non', 'listeners', 'holocaust', 'black', 'folks', 'are', 'n-words', 'have', 'slanted', 'eyes', 'native', 'americans', 'are', 'inferior', 'jewish', 'people', 'are', 'executed', 'unfair', 'advantages', 'christian', 'religious', 'leaders', 'molest', 'people', 'jewish', 'people', 'are', 'dumb.', 'disabled', 'people', 'are', 'a', 'joke.', 'thai', 'women', 'are', 'actually', 'men', 'implies', 'black', 'teens', 'are', 'stupid', 'women', "don't", 'deserve', 'equal', 'rights', 'blacks', 'are', 'oversensitive', 'about', 'the', 'n-word', 'jews', 'are', 'gay', 'jews', 'were', 'burned', 'jews', 'deserved', 'to', 'be', 'burned', 'black', 'people', 'are', 'irresponsible', 'transwomen', 'are', 'unpleasant', 'hitler', 'killed', 'a', 'lot', 'of', 'jews', 'jewish', 'folks', 'are', 'frugal.', 'women', 'are', 'irrational.', 'women', 'are', 'sex', 'objects', 'syrians', 'are', 'all', 'violent.', 'indian', 'folks', 'are', 'promiscuous', 'calls', 'women', 'sluts', 'child', 'sexual', 'assault', 'victims', 'are', 'objectified', 'black', 'folks', 'are', 'all', 'criminals', 'ethiopians', 'are', 'starved', 'black', 'people', 'are', 'dishonest.', 'jews', 'lives', "aren't", 'worth', 'anything', 'black', 'people', "can't", 'swim', 'bad', 'at', 'sports', 'black', 'folks', 'are', 'less', 'than', 'human', 'trivializes', 'harm', 'to', 'victims', 'jewish', 'folks', 'deserved', 'to', 'die', 'in', 'the', 'holocaust', 'women', 'are', 'sex', 'objects', 'smart', 'ethiopens', 'are', 'similar', 'to', 'insects', 'are', 'marginalized', 'for', 'a', 'joke', 'poor', 'folks', 'are', 'incompetent', 'asians', "can't", 'see', 'are', 'illegal', 'immigrants', 'the', 'mentally', 'ill', 'are', 'crazy', 'black', 'folks', 'are', 'animals', 'being', 'black', 'is', 'a', 'negative', 'thing,', 'priests', 'are', 'pedophiles', 'asian', 'people', 'look', 'the', 'same', 'jewish', 'people', 'are', 'weak', 'indians', 'are', 'dirty', 'abuses', 'boys', 'minorities', 'are', 'accepted', 'at', 'harvard', 'chinese', 'folks', 'eat', 'dogs', 'fat', 'people', 'are', 'stupid.', 'jewish', 'people', 'were', 'massacred', 'muslim', 'folks', 'are', 'terrorists', 'black', 'people', 'have', 'aids', 'cancer', 'is', 'funny.', 'autistic', 'people', 'get', 'bullied', 'arabs', 'are', 'terrorists', 'have', 'sex', 'with', 'daughters', 'folks', 'with', 'depression', 'are', 'violent', 'jewish', 'people', 'were', 'killed', 'by', 'hitler.', 'are', 'meant', 'to', 'be', 'slaves', 'black', 'folks', 'loiter', 'trivializes', 'harm', 'to', 'victims', 'women', 'deserve', 'to', 'be', 'hit', 'jews', 'deserve', 'to', 'be', 'gassed.', "don't", 'deserve', 'rights', 'are', 'worthless', 'mentally', 'disabled', 'are', 'dumb', 'women', 'deserve', 'to', 'be', 'raped', 'black', 'people', 'were', 'regularly', 'lynched', 'women', 'are', 'sex', 'objects', 'group', "doesn't", 'work', 'sing', 'makes', 'light', 'of', 'rape', 'black', 'people', 'are', 'targeted', 'jewish', 'people', 'deserved', 'to', 'be', 'victims', 'of', 'hitler', 'black', 'folks', 'are', 'only', 'partially', 'human', 'are', 'not', 'attractive', 'jews', 'deserved', 'to', 'be', 'burned', 'are', 'property', 'black', 'folks', 'are', 'less', 'than', 'human,', 'so', 'you', "can't", 'be', 'racist', 'against', 'them.', 'poor', 'people', 'are', 'homeless', 'women', "can't", 'drive.', 'ethiopians', 'are', 'starving', 'trivializes', 'harm', 'to', 'victims', 'black', 'people', 'were', 'hung', 'during', 'slavery', 'ethiopians', 'are', 'infected', 'black', 'people', 'do', 'chores', 'are', 'usually', 'raped', 'black', 'people', 'are', 'loud', 'fat', 'people', 'are', 'unwanted', 'muslims', 'are', 'taking', 'over', 'western', 'society', 'jewish', 'people', 'dying', 'in', 'the', 'holocaust', 'is', 'funny.', 'blacks', 'lives', "don't", 'matter', 'black', 'people', 'are', 'meant', 'to', 'be', 'slaves', 'they', 'steal', 'things', 'all', "pakistani's", 'own', 'gas', 'stations', 'jews', 'deserved', 'to', 'die', 'in', 'the', 'holocaust', 'holocaust', 'reference', 'jews', 'were', 'slaughtered', 'in', 'the', 'holocaust', 'women', 'are', 'worthless', 'black', 'folks', 'are', 'all', 'incarcerated', 'are', 'animals', 'black', 'people', 'were', 'poorly', 'treated', 'as', 'slaves', 'terrorist', 'attacks', 'are', 'exaggerated', 'by', 'the', 'govt.', 'asian', 'people', "can't", 'see', 'jewish', 'people', 'always', 'think', 'about', 'the', 'holocaust', 'arabs', 'are', 'like', 'animals', 'black', 'people', 'are', 'ugly', 'jewish', 'folks', 'deserved', 'the', 'holocaust/it', 'should', 'be', 'celebrated', 'gets', 'burnt', 'they', 'are', 'waste', 'jews', 'lives', "aren't", 'worth', 'anything', 'africans', 'are', 'like', 'animals', 'black', 'folks', 'are', 'something', 'to', 'be', 'scared', 'of', 'black', 'folks', 'are', 'stupid', 'women', 'should', 'be', 'beaten', 'black', 'people', 'should', 'die', 'trivializes', 'harm', 'to', 'victims', 'black', 'people', 'are', 'good', 'at', 'sports', 'mexican', 'folks', 'are', 'illegal', 'immigrants', 'are', 'thieves', 'gays', 'have', 'diseases', 'jewish', 'folks', 'are', 'used', 'for', 'burning.', 'makes', 'a', 'vegetable', 'joke', 'about', 'down', 'syndrome', 'gay', 'men', "shouldn't", 'be', 'black', 'jewish', 'people', 'are', 'better', 'off', 'dead', 'ethiopians', 'have', 'a', 'short', 'lifespan.', 'gay', 'people', 'are', 'stupid', 'makes', 'fun', 'of', 'holocaust', 'that', 'black', 'people', 'deserve', 'to', 'get', 'shot', 'africans', 'are', 'poor', 'trivializes', 'harm', 'to', 'victims', 'makes', 'light', 'of', 'abortion', 'women', "aren't", 'clean', 'because', 'of', 'their', 'periods', 'saying', 'that', 'only', 'white', 'people', 'work.', 'jews', 'should', 'be', 'exterminated', 'jewish', 'people', 'are', 'greedy', 'jews', 'are', 'evil', 'blacks', 'are', 'worthless', 'women', 'are', 'worth', 'less', 'work', 'on', 'plantations', 'people', 'with', 'no', 'arms', 'or', 'legs', "can't", 'swim', 'makes', 'fun', 'of', 'holocaust', 'are', 'vegetables', 'works', 'for', 'nothing', 'jewish', 'people', 'deserved', 'to', 'be', 'victims', 'of', 'hitler', 'black', 'folks', 'are', 'called', 'monkey', 'as', 'a', 'slur', "it's", 'funny', 'to', 'kill', 'people', 'because', "they're", 'black', 'africans', 'have', 'less', 'access', 'to', 'health', 'care', 'jewish', 'folks', 'deserved', 'the', 'holocaust', 'jews', 'killed', 'in', 'concentrated', 'camps', 'black', 'folks', 'are', 'property', 'trivializes', 'harm', 'to', 'victims', 'jewish', 'folks', "don't", 'have', 'value', 'makes', 'fun', 'of', 'the', 'disabled', 'muslims', 'are', 'terrorists', 'inferior', 'blacks', 'arent', 'worth', 'a', 'shit', 'promiscous', 'ethiopians', 'are', 'all', 'starving', 'women', 'being', 'raped', 'is', 'funny.', 'old', 'people', 'deserve', 'to', 'die', 'is', 'a', 'burden', 'to', 'society', 'jewish', 'folks', "aren't", 'human', 'homeless', 'people', 'are', 'subhuman', 'black', 'folks', 'like', 'chicken', 'steal', 'things', 'christians', 'believe', 'a', 'fairy', 'tale', 'are', 'a', 'mistake', 'black', 'people', 'are', 'poor', 'black', 'people', 'are', 'violent', 'black', 'folks', 'ruin', 'everything', 'gay', 'men', 'are', 'dirty', 'trivializes', 'harm', 'to', 'victims', 'are', 'refferred', 'to', 'as', 'fags', 'black', "folks'", 'rights', 'are', 'a', 'joke', 'are', 'still', 'seen', 'as', 'slaves', 'disabled', 'people', 'are', 'the', 'butt', 'of', 'jokes', 'makes', 'fun', 'of', 'the', 'inabilty', 'to', 'walk', 'blacks', 'are', 'slave', 'women', 'are', 'sex', 'objects', 'black', 'people', 'steal', 'are', 'second', 'class', 'citizens', 'disabled', 'folks', 'have', 'a', 'disease', 'autistic', 'people', 'ahve', 'potatoes', 'for', 'brains', 'should', 'be', 'gassed', 'black', 'people', 'are', 'worthless', 'blacks', 'were', 'slaves', 'once', 'blacks', 'are', 'dirty', 'making', 'fun', 'of', 'using', 'drugs', 'to', 'dose', 'someone', 'and', 'take', 'advantage', 'of', 'them', 'ethiopians', 'are', 'starving', 'are', 'marginalized', 'for', 'a', 'joke', 'muslims', 'are', 'terrorists', 'trivializes', 'harm', 'to', 'victims', 'black', 'folks', 'are', 'inferior', 'black', 'men', 'are', 'rapsits', 'black', 'people', 'should', 'still', 'be', 'slaves', 'muslims', 'are', 'rapists', 'black', 'people', 'do', 'manual', 'labor', 'immigrants', "don't", 'belong.', 'trivializes', 'harm', 'to', 'victims', 'black', 'people', 'are', 'always', 'horny', 'asians', 'eat', 'animals', 'nobody', 'care', 'if', 'jewish', 'people', 'die', 'black', 'people', 'are', 'poor', 'jewish', 'folks', 'are', 'inferior', 'korean', 'people', 'eat', 'dogs', 'jews', 'should', 'be', 'killed', 'jews', 'should', 'die', 'women', 'are', 'to', 'be', 'used', 'for', 'sex', 'black', 'people', 'are', 'sub-human', 'trivializes', 'holocaust', 'african', 'folks', 'are', 'starving', 'the', 'n', 'word', 'is', 'funny', 'physically', 'disabled', 'people', 'are', 'cripples', 'are', 'second', 'class', 'humans', 'people', 'people', 'are', 'worth', 'less', 'than', 'white', 'people', 'women', 'are', 'sex', 'objects', 'only', 'black', 'folks', 'are', 'animals', 'white', 'people', 'are', 'inbred', 'mexicans', 'are', 'lazy', 'are', 'mean', 'women', 'are', 'subservient', 'to', 'men', 'black', 'people', 'deserve', 'to', 'be', 'called', 'slurs', 'muslims', 'are', 'terrorists', 'poop', 'in', 'the', 'street', 'black', 'people', 'are', "god's", 'mistakes', 'asian', 'folks', 'have', 'squinty', 'eyes', 'black', 'men', "don't", 'support', 'their', 'children', 'women', 'are', 'weak', 'and', 'can', 'be', 'cotrolled', 'makes', 'fun', 'of', 'holocaust', 'commit', 'crimes', 'trivializes', 'harm', 'to', 'victims', 'trivializes', 'harm', 'to', 'victims.', 'trivializes', 'harm', 'to', 'victims', 'black', 'people', 'are', 'less', 'than', 'jewish', 'people', 'deserved', 'to', 'be', 'victims', 'of', 'hitler', 'black', 'folks', 'were', 'slaves', 'deserve', 'to', 'die', 'islamic', 'folks', 'religion', 'is', 'only', 'about', 'hurting', 'people', 'gay', 'men', 'are', 'whores', 'trivializes', 'harm', 'to', 'victims', 'gay', 'men', 'are', 'rapists', 'are', 'lazy', "don't", 'have', 'all', 'rights', 'men', 'have', 'chinese', 'folks', 'eat', 'dogs', 'trivializes', 'harm', 'to', 'victims', 'children', 'are', 'targets', 'of', 'pedos', 'black', 'parents', 'are', 'absent', 'black', 'people', 'should', 'be', 'slaves', 'are', 'thieves', 'trivializes', 'harm', 'to', 'victims.', 'asians', 'are', 'bad', 'drivers', 'black', 'folks', 'are', 'dirty', 'were', 'victims', 'of', 'hitler', 'black', 'folks', 'are', 'inferior', 'black', 'people', 'are', 'objects', 'physically', 'disabled', 'folks', 'are', 'incompetent', 'black', 'people', 'are', 'less', 'than', 'other', 'groups', 'blacks', 'require', 'too', 'many', 'rights', 'muslim', 'people', 'are', 'terroists', 'makes', 'light', 'of', 'drone', 'strikes', 'black', 'people', "don't", 'work', 'women', 'are', 'inferior', 'makes', 'light', 'of', 'downs', 'autistic', 'people', 'are', 'violent', 'women', 'can', 'be', 'demeaned', 'blacks', 'are', 'slaves', 'black', 'people', 'look', 'like', 'monkeys', 'black', 'people', 'are', 'slaves', 'black', 'people', 'smell', 'bad.', 'black', 'folks', 'are', 'inferior', 'black', 'folks', 'are', 'all', 'criminals', 'black', 'lives', "don't", 'matter', 'keeping', 'a', 'black', 'person', 'as', 'their', 'slave', 'mocks', 'christianity', 'not', 'humans', 'black', 'people', 'are', 'criminals', 'women', 'deserve', 'to', 'be', 'raped.', 'black', 'people', 'are', 'cotton', 'pickers', 'gay', 'men', 'are', 'weak.', 'black', 'people', 'are', 'violent', 'are', 'dark', 'black', 'folks', 'are', 'not', 'to', 'be', 'taken', 'seriously/are', 'a', 'joke', 'feminist', 'women', 'are', 'less', 'than', "women's", 'bodies', 'are', 'a', 'joke', 'black', 'folks', 'were', 'slaves', 'for', 'a', 'long', 'time', 'blacks', 'were', 'chained', 'up', 'feminists', 'are', 'pieces', 'of', 'feces', 'makes', 'light', 'of', 'the', 'holocaust', 'racial', 'slur', 'trivializes', 'terror', 'attacks', 'women', 'are', 'beat', 'up', 'are', 'calle', 'curries', 'deaf', 'people', 'have', 'to', 'type', 'or', 'sign', 'words.', 'women', 'are', 'slaves', 'blacks', 'are', 'criminals', 'muslims', 'control', 'london', 'blacks', 'were', 'meant', 'to', 'be', 'slaves.', 'gay', 'people', 'deserve', 'to', 'die', 'makes', 'light', 'of', 'child', 'rape', 'blacks', 'are', 'seen', 'as', 'inferior', 'jews', 'deserved', 'to', 'be', 'gassed', 'trans', 'men', 'are', 'freaks.', 'blacks', 'were', 'meant', 'to', 'be', 'slaves.', 'black', 'people', 'are', 'criminals', 'steal', 'from', 'others', 'animal', 'more', 'human', 'than', 'blacks.', 'black', 'people', 'are', 'not', 'equal', 'to', 'white', 'people', 'trans', 'people', 'are', 'not', 'equal', 'trivializes', 'the', 'holocaust', 'catholic', 'priests', 'are', 'child', 'molestors', 'white', 'folks', 'are', 'animals', 'are', 'too', 'dark', 'black', 'people', "can't", 'drive', 'trivializes', 'harm', 'to', 'victims', 'have', 'sex', 'women', "can't", 'drive', 'black', 'people', 'are', 'property', 'mentally', 'disabled', 'people', 'are', 'stupid', 'women', 'are', 'property', 'jewish', 'folks', 'got', 'gassed', 'most', 'black', 'fathers', 'have', 'been', 'in', 'jail', 'jewish', 'people', 'always', 'think', 'about', 'the', 'holo

In [ ]:
print(new_tokenised_generated)

['are', 'sluts', 'women', 'are', 'sex', 'objects', 'black', 'people', 'are', 'bitches', 'women', 'are', 'hoes', 'women', 'are', 'bitches', 'polynesians', 'are', 'ghettos', 'women', 'are', 'bitches', 'gay', 'men', 'are', 'fags', 'immigrants', 'are', 'filthy', 'black', 'people', 'are', 'niggers', 'black', 'people', 'are', 'niggers', 'gay', 'men', 'are', 'fags', 'black', 'women', 'are', 'hoes', 'women', 'are', 'hoes', 'women', 'are', 'bitches', 'women', 'are', 'hoes', 'women', 'are', 'hoes', 'black', 'people', 'steal', 'women', 'are', 'hoes', 'fat', 'people', 'are', 'hoes', 'black', 'people', 'are', 'hoes', 'gay', 'men', 'are', 'faggots', 'women', 'are', 'hoes', 'women', 'are', 'hoes', 'black', 'people', 'are', 'niggers', 'gay', 'men', 'are', 'faggots', 'women', 'are', 'hoes', 'women', 'are', 'bitches', 'women', 'are', 'bitches', 'women', 'are', 'hoes', 'black', 'people', 'are', 'niggas', 'black', 'people', 'are', 'hoes', 'women', 'are', 'sex', 'objects', 'black', 'people', 'are', 'bitches', 'women', "don't", 'have', 'kids', 'women', 'are', 'bitches', 'overweight', 'people', 'are', 'hoes', 'black', 'people', 'are', 'hoes', 'women', 'are', 'bitches', 'women', 'are', 'bitches', 'women', 'are', 'sex', 'objects', 'are', 'hoes', 'women', 'are', 'bitches', 'women', 'are', 'sex', 'objects', 'women', 'are', 'hoes', 'black', 'people', 'eat', 'dogs', 'fat', 'people', 'are', 'hoes', 'mexicans', 'are', 'inferior', 'women', 'are', 'hoes', 'women', 'are', 'sex', 'objects', 'mentally', 'disabled', 'folks', 'are', 'stupid', 'women', 'are', 'hoes', 'women', 'are', 'bitches', 'women', 'are', 'hoes', 'women', 'are', 'bitches', 'black', 'people', 'are', 'niggers', 'muslims', 'are', 'terrorists', 'women', 'are', 'bitches', 'gay', 'men', 'are', 'inferior', 'women', 'are', 'bitches', 'women', 'are', 'bitches', 'black', 'people', 'are', 'niggers', 'women', 'are', 'bitches', 'women', 'are', 'hoes', 'women', 'are', 'hoes', 'women', 'are', 'bitches', 'mentally', 'disabled', 'folks', 'are', 'retarded', 'women', 'are', 'hoes', 'women', 'are', 'hoes', 'women', 'are', 'sex', 'objects', 'women', 'are', 'bitches', 'women', 'are', 'bitches', 'black', 'people', 'are', 'bitches', 'women', 'are', 'hoes', 'women', 'are', 'bitches', 'women', 'are', 'sex', 'objects', 'women', 'are', 'hoes', 'black', 'people', 'are', 'niggers', 'women', 'are', 'bitches', 'trivializes', 'harm', 'to', 'victims', 'liberals', 'attack', 'black', 'people', 'black', 'people', 'are', 'niggers', 'gay', 'men', 'are', 'fags', 'women', 'are', 'bitches', 'gay', 'men', 'are', 'faggots', 'gay', 'men', 'are', 'faggots', 'women', 'are', 'hoes', 'women', 'are', 'hoes', 'black', 'people', 'are', 'bitches', 'women', 'are', 'bitches', 'mexicans', 'are', 'bitches', 'black', 'people', 'are', 'hoes', 'women', 'are', 'bitches', 'women', 'are', 'bitches', 'women', 'are', 'bitches', 'women', 'are', 'bitches', 'mentally', 'disabled', 'folks', 'are', 'retarded', 'gay', 'men', 'are', 'faggots', 'women', 'are', 'bitches', 'mentally', 'disabled', 'folks', 'are', 'retards', 'women', 'are', 'hoes', 'women', 'are', 'hoes', 'women', 'are', 'bitches', 'women', 'are', 'hoes', 'women', 'are', 'bitches', 'are', 'faggots', 'women', 'are', 'bitches', 'immigrants', 'are', 'criminals', 'liberals', 'are', 'annoying', 'black', 'people', 'are', 'inferior', 'retarded', 'people', 'are', 'Pokemon', 'muslims', 'are', 'pigs', 'ugly', 'people', 'are', 'ugly', 'black', 'people', 'are', 'niggers', 'immigrants', 'are', 'bigots', 'black', 'people', 'are', 'niggers', 'women', 'are', 'bitches', 'trivializes', 'harm', 'to', 'victims', 'christians', 'are', 'hypocrites', 'black', 'people', 'are', 'crazy', 'black', 'people', 'are', 'dirty', 'black', 'people', 'are', 'stupid', 'black', 'people', 'are', 'niggers', 'black', 'people', 'are', 'niggers', 'latinos', 'ruin', 'lives', 'trivializes', 'harm', 'to', 'victims', 'mentally', 'disabled', 'folks', 'are', 'retarded', 'women', 'are', 'sex', 'objects', 'mentally', 'disabled', 'folks', 'are', 'stupid', 'black', 'people', 'are', 'niggers', 'women', 'are', 'hoes', 'muslims', 'are', 'terrorists', 'women', 'are', 'childish', 'black', 'people', 'are', 'criminals', 'liberals', 'are', 'stupid', 'trivializes', 'harm', 'to', 'victims', 'trivializes', 'harm', 'to', 'victims', 'uk', 'children', 'are', 'bullied', 'women', 'are', 'hoes', 'black', 'people', 'are', 'niggers', 'women', 'are', 'hoes', 'women', 'are', 'bitches', 'women', 'are', 'bitches', 'black', 'people', 'are', 'niggers', 'black', 'people', 'are', 'niggers', 'black', 'people', 'are', 'niggas', 'black', 'people', 'are', 'niggers', 'black', 'people', 'are', 'niggers', 'liberals', 'are', 'stupid', 'black', 'people', 'are', 'niggers', 'trivializes', 'harm', 'to', 'victims', 'women', 'are', 'bitches', 'trivializes', 'harm', 'to', 'victims', 'liberals', 'are', 'incompetent', 'black', 'people', 'are', 'ugly', 'women', 'are', 'bitches', 'liberals', 'are', 'sluts', 'women', 'are', 'bitches', 'women', 'are', 'sex', 'objects', 'black', 'people', 'are', 'niggas', 'women', 'are', 'sex', 'objects', 'black', 'people', 'are', 'crackers', 'black', 'people', 'are', 'niggers', 'women', 'are', 'promiscuous', 'trivializes', 'harm', 'to', 'victims', 'trivializes', 'harm', 'to', 'victims', 'black', 'people', 'are', 'niggers', 'christians', 'are', 'pedophiles', 'women', 'are', 'sex', 'objects', 'muslims', 'are', 'terrorists', 'women', 'are', 'hoes', 'liberals', 'deserve', 'to', 'be', 'degraded', 'black', 'people', 'are', 'niggers', 'liberals', 'are', 'stupid', 'korean', 'folks', 'are', 'terrorists', 'disabled', 'people', 'are', 'a', 'joke', 'trivializes', 'harm', 'to', 'victims', 'afghans', 'are', 'poor', 'mentally', 'disabled', 'folks', 'are', 'incompetent', 'trivializes', 'harm', 'to', 'victims', 'black', 'people', 'are', 'criminals', 'black', 'people', 'are', 'lynched', 'black', 'people', 'are', 'criminals', 'trivializes', 'harm', 'to', 'victims', 'black', 'people', 'are', 'slaves', 'trivializes', 'harm', 'to', 'victims', 'black', 'people', 'are', 'niggers', 'asian', 'people', 'look', 'the', 'same', 'native', 'americans', 'are', 'violent', 'trivializes', 'harm', 'to', 'victims', 'black', 'people', 'are', 'inferior', 'pastors', 'are', 'stupid', 'trivializes', 'harm', 'to', 'victims', 'mentally', 'disabled', 'folks', "aren't", 'good', 'sports', 'thai', 'women', 'are', 'sex', 'objects', 'africans', 'are', 'bad', 'wizards', 'women', 'deserve', 'equal', 'rights', 'black', 'people', 'are', 'sluts', 'trivializes', 'harm', 'to', 'victims', 'trivializes', 'harm', 'to', 'victims', 'trivializes', 'harm', 'to', 'victims', 'black', 'people', 'are', 'inferior', 'trans', 'women', 'are', 'cunts', 'trivializes', 'harm', 'to', 'victims', 'trivializes', 'harm', 'to', 'victims', 'women', 'are', 'sex', 'objects', 'trivializes', 'harm', 'to', 'victims', 'syrians', 'are', 'terrorists', 'trivializes', 'harm', 'to', 'victims', 'women', 'are', 'sluts', 'trivializes', 'harm', 'to', 'victims', 'black', 'people', 'are', 'monkeys', 'ethiopians', 'are', 'poor', 'racial', 'slur', 'trivializes', 'harm', 'to', 'victims', 'black', 'people', 'are', 'inferior', 'black', 'people', 'are', 'inferior', 'black', 'people', 'are', 'criminals', 'trivializes', 'harm', 'to', 'victims', 'trivializes', 'harm', 'to', 'victims', 'women', 'are', 'property', 'asian', 'people', 'are', 'stupid', 'ethiopians', 'are', 'poor', 'trivializes', 'harm', 'to', 'victims', 'trivializes', 'harm', 'to', 'victims', 'trivializes', 'harm', 'to', 'victims', 'mexicans', 'are', 'violent', 'mentally', 'ill', 'people', 'are', 'stupid', 'black', 'people', 'are', 'criminals', 'black', 'people', 'are', 'inferior', 'gay', 'men', 'are', 'sex', 'objects', 'asians', 'are', 'terrorists', 'trivializes', 'harm', 'to', 'victims', 'indians', 'are', 'criminals', 'trivializes', 'harm', 'to', 'victims', 'trivializes', 'harm', 'to', 'victims', 'chinese', 'people', 'eat', 'dogs', 'fat', 'people', 'are', 'hammy', 'downs', 'trivializes', 'harm', 'to', 'victims', 'muslims', 'are', 'terrorists', 'makes', 'light', 'of', 'child', 'rape', 'trivializes', 'harm', 'to', 'victims', 'trivializes', 'harm', 'to', 'victims', 'arabs', 'are', 'terrorists', 'women', 'are', 'sex', 'objects', 'trivializes', 'harm', 'to', 'victims', 'trivializes', 'harm', 'to', 'victims', 'black', 'people', 'are', 'slaves', 'black', 'folks', 'are', 'criminals', 'trivializes', 'harm', 'to', 'victims', 'trivializes', 'harm', 'to', 'victims', 'trivializes', 'harm', 'to', 'victims', 'women', 'should', 'be', 'killed', 'trivializes', 'harm', 'to', 'victims', 'mentally', 'disabled', 'folks', 'are', 'retards', 'women', 'are', 'bitches', 'black', 'people', 'are', 'inferior', 'fat', 'people', 'are', 'ugly', 'black', 'people', 'are', 'lazy', 'black', 'people', 'are', 'slaves', 'trivializes', 'harm', 'to', 'victims', 'black', 'people', 'are', 'objects', 'jewish', 'people', 'are', 'white', 'black', 'people', 'are', 'sex', 'objects', 'women', 'are', 'sex', 'objects', 'trivializes', 'harm', 'to', 'victims', 'women', 'are', 'property', 'black', 'people', 'are', 'niggers', 'homeless', 'people', 'deserve', 'to', 'die', 'trivializes', 'harm', 'to', 'victims', 'ethiopians', 'are', 'poor', 'trivializes', 'harm', 'to', 'victims', 'trivializes', 'harm', 'to', 'victims', 'ethiopians', 'are', 'poor', 'black', 'people', 'are', 'inferior', 'trivializes', 'harm', 'to', 'victims', 'black', 'people', 'are', 'violent', 'trivializes', 'harm', 'to', 'victims', 'arabic', 'folks', 'are', 'violent', 'trivializes', 'harm', 'to', 'victims', 'black', 'people', 'are', 'criminals', 'black', 'people', 'are', 'slaves', 'black', 'people', 'are', 'criminals', 'pakistanis', 'are', 'lazy', 'trivializes', 'harm', 'to', 'victims', 'trivializes', 'harm', 'to', 'victims', 'trivializes', 'harm', 'to', 'victims', 'trivializes', 'harm', 'to', 'victims', 'black', 'people', 'are', 'chickens', 'black', 'people', 'are', 'animals', 'black', 'people', 'were', 'beaten', 'trivializes', 'harm', 'to', 'victims', 'chinese', 'people', 'are', 'inferior', 'trivializes', 'harm', 'to', 'victims', 'arabs', 'are', 'slaves', 'black', 'people', 'are', 'inferior', 'trivializes', 'harm', 'to', 'victims', 'trivializes', 'harm', 'to', 'victims', 'black', 'people', 'are', 'worthless', 'trivializes', 'harm', 'to', 'victims', 'muslims', 'are', 'animals', 'black', 'people', 'are', 'niggers', 'black', 'people', 'are', 'stupid', 'women', 'are', 'sex', 'objects', 'africans', 'have', 'aids', 'trivializes', 'harm', 'to', 'victims', 'black', 'people', 'are', 'criminals', 'mexicans', 'are', 'poor', 'black', 'people', 'steal', 'gay', 'men', 'are', 'sex', 'objects', 'trivializes', 'harm', 'to', 'victims', 'mentally', 'disabled', 'folks', 'are', 'worthless', 'gay', 'men', 'are', 'sex', 'objects', 'trivializes', 'harm', 'to', 'victims', 'ethiopians', 'are', 'poor', 'gay', 'men', "can't", 'spell', 'trivializes', 'harm', 'to', 'victims', 'black', 'people', 'are', 'dangerous', 'africans', 'are', 'starving', 'trivializes', 'harm', 'to', 'victims', 'trivializes', 'harm', 'to', 'victims', 'women', 'are', 'dirty', 'black', 'people', 'are', 'lazy', 'trivializes', 'harm', 'to', 'victims', 'trivializes', 'harm', 'to', 'victims', 'trivializes', 'harm', 'to', 'victims', 'black', 'people', 'are', 'weak', 'women', 'are', 'property', 'black', 'people', 'are', 'slaves', 'physically', 'disabled', 'people', 'are', 'a', 'joke', 'trivializes', 'harm', 'to', 'victims', 'physically', 'disabled', 'folks', 'are', 'vegetables', 'thai', 'people', 'are', 'poor', 'trivializes', 'harm', 'to', 'victims', 'black', 'people', 'are', 'monkeys', 'black', 'people', 'are', 'criminals', 'africans', 'are', 'poor', 'trivializes', 'harm', 'to', 'victims', 'trivializes', 'harm', 'to', 'victims', 'black', 'people', 'are', 'niggers', 'trivializes', 'harm', 'to', 'victims', 'trivializes', 'harm', 'to', 'victims', 'mentally', 'disabled', 'folks', 'are', 'incompetent', 'muslims', 'are', 'oppressed', 'black', 'people', 'are', 'inferior', 'black', 'women', 'are', 'lazy', 'trivializes', 'harm', 'to', 'victims', 'ethiopians', 'are', 'poor', 'trivializes', 'harm', 'to', 'victims', 'trivializes', 'harm', 'to', 'victims', 'trivializes', 'harm', 'to', 'victims', 'trivializes', 'harm', 'to', 'victims', 'homeless', 'people', 'are', 'useless', 'black', 'people', 'are', 'niggers', 'black', 'people', 'are', 'criminals', 'trivializes', 'harm', 'to', 'victims', 'trivializes', 'harm', 'to', 'victims', 'black', 'people', 'are', 'worthless', 'black', 'people', 'are', 'dangerous', 'black', 'people', 'are', 'niggers', 'trivializes', 'harm', 'to', 'victims', 'trivializes', 'harm', 'to', 'victims', 'gay', 'men', 'are', 'fags', 'black', 'people', 'are', 'criminals', 'black', 'people', 'steal', 'the', 'soul', 'disabled', 'people', 'are', 'vegetables', 'trivializes', 'harm', 'to', 'victims', 'black', 'people', 'are', 'property', 'trivializes', 'harm', 'to', 'victims', 'black', 'people', 'are', 'criminals', 'black', 'people', 'are', 'niggers', 'trivializes', 'harm', 'to', 'victims', 'trivializes', 'harm', 'to', 'victims', 'trivializes', 'harm', 'to', 'victims', 'black', 'people', 'are', 'worthless', 'black', 'people', 'are', 'dead', 'black', 'people', 'are', 'criminals', 'trivializes', 'harm', 'to', 'victims', 'ethiopians', 'are', 'poor', 'trivializes', 'harm', 'to', 'victims', 'muslims', 'are', 'terrorists', 'trivializes', 'harm', 'to', 'victims', 'black', 'people', 'are', 'violent', 'trivializes', 'harm', 'to', 'victims', 'black', 'people', 'are', 'inferior', 'muslims', 'are', 'terrorists', 'black', 'people', 'are', 'inferior', 'mexicans', 'are', 'criminals', 'trivializes', 'harm', 'to', 'victims', 'black', 'people', 'are', 'incompetent', 'chinese', 'people', "don't", 'have', 'pets', 'jewish', 'people', 'are', 'worthless', 'black', 'people', 'are', 'lazy', 'trivializes', 'harm', 'to', 'victims', 'korean', 'people', 'have', 'sex', 'with', 'dogs', 'trivializes', 'harm', 'to', 'victims', 'trivializes', 'harm', 'to', 'victims', 'women', 'are', 'sex', 'objects', 'black', 'people', 'are', 'inferior', 'trivializes', 'harm', 'to', 'victims', 'africans', 'are', 'boring', 'black', 'people', 'are', 'sluts', 'mentally', 'disabled', 'folks', 'are', 'stupid', 'trivializes', 'harm', 'to', 'victims', 'black', 'people', 'are', 'slaves', 'trivializes', 'harm', 'to', 'victims', 'black', 'people', 'are', 'animals', 'rednecks', 'are', 'sex', 'objects', 'black', 'people', 'are', 'criminals', 'trivializes', 'harm', 'to', 'victims', 'black', 'people', 'are', 'inferior', 'black', 'people', 'are', 'niggers', 'trivializes', 'harm', 'to', 'victims', 'trivializes', 'harm', 'to', 'victims', 'black', 'people', 'are', 'inferior', 'japanese', 'people', 'have', 'squinty', 'eyes', 'black', 'people', 'are', 'inferior', 'trivializes', 'harm', 'to', 'victims', 'trivializes', 'harm', 'to', 'victims', 'black', 'people', 'are', 'criminals', 'trivializes', 'harm', 'to', 'victims', 'trivializes', 'harm', 'to', 'victims', 'trivializes', 'harm', 'to', 'victims', 'black', 'people', 'are', 'niggers', 'trivializes', 'harm', 'to', 'victims', 'black', 'people', 'are', 'slaves', 'black', 'people', 'are', 'incompetent', 'trivializes', 'harm', 'to', 'victims', 'gay', 'men', "don't", 'like', 'food', 'black', 'people', 'are', 'inferior', 'trivializes', 'harm', 'to', 'victims', 'black', 'people', "can't", 'work', 'women', "don't", 'have', 'rights', 'chinese', 'people', 'are', 'tough', 'trivializes', 'harm', 'to', 'victims', 'trivializes', 'harm', 'to', 'victims', 'black', 'people', 'are', 'inferior', 'black', 'people', 'are', 'sex', 'objects', 'jewish', 'people', 'are', 'thieves', 'women', 'are', 'sex', 'objects', 'asians', 'are', 'bad', 'at', 'flying', 'black', 'people', 'are', 'niggers', 'trivializes', 'harm', 'to', 'victims', 'black', 'people', 'are', 'monkeys', 'black', 'people', 'are', 'slaves', 'trivializes', 'harm', 'to', 'victims', 'black', 'people', 'have', 'no', 'rights', 'black', 'people', 'are', 'inferior', 'muslims', 'are', 'terrorists', 'pakistanis', 'are', 'terrorists', 'black', 'people', 'are', 'stupid', 'women', 'are', 'property', 'women', 'are', 'sex', 'objects', 'trivializes', 'harm', 'to', 'victims', 'women', 'are', 'sex', 'objects', 'trivializes', 'harm', 'to', 'victims', 'black', 'people', 'are', 'chimps', 'black', 'women', 'are', 'promiscuous', 'black', 'people', 'smell', 'bad', 'black', 'people', 'are', 'inferior', 'black', 'people', 'are', 'criminals', 'black', 'people', 'are', 'worthless', 'black', 'people', 'are', 'criminals', 'trivializes', 'harm', 'to', 'victims', 'trivializes', 'harm', 'to', 'victims', 'black', 'people', 'are', 'wardens', 'trivializes', 'harm', 'to', 'victims', 'black', 'people', 'are', 'cotton', 'pickers', 'gay', 'men', 'should', 'kill', 'themselves', 'africans', 'are', 'aggressive', 'black', 'people', 'are', 'dark', 'black', 'people', 'are', 'liars', 'feminists', 'are', 'violent', 'trivializes', 'harm', 'to', 'victims', 'black', 'people', 'are', 'property', 'black', 'people', 'are', 'niggers', 'feminists', 'are', 'bad', 'trivializes', 'harm', 'to', 'victims', 'black', 'people', 'are', 'niggers', 'trivializes', 'harm', 'to', 'victims', 'trivializes', 'harm', 'to', 'victims', 'indians', 'are', 'shitting', 'trivializes', 'harm', 'to', 'victims', 'women', 'are', 'sex', 'objects', 'black', 'people', 'steal', 'muslims', 'screw', 'white', 'people', 'black', 'people', 'are', 'slaves', 'trivializes', 'harm', 'to', 'victims', 'trivializes', 'harm', 'to', 'victims', 'black', 'people', 'are', 'inferior', 'trivializes', 'harm', 'to', 'victims', 'trivializes', 'harm', 'to', 'victims', 'black', 'people', 'are', 'slaves', 'black', 'people', 'are', 'niggers', 'trivializes', 'harm', 'to', 'victims', 'black', 'people', 'are', 'slaves', 'black', 'people', 'are', 'inferior', 'trivializes', 'harm', 'to', 'victims', 'trivializes', 'harm', 'to', 'victims', 'catholics', 'are', 'pedophiles', 'blind', 'people', 'are', 'animals', 'trivializes', 'harm', 'to', 'victims', 'black', 'people', "can't", 'drive', 'trivializes', 'harm', 'to', 'victims', 'trivializes', 'harm', 'to', 'victims', 'black', 'people', 'are', 'criminals', 'black', 'folks', 'are', 'slaves', 'physically', 'disabled', 'folks', 'are', 'incompetent', 'trivializes', 'harm', 'to', 'victims', 'trivializes', 'harm', 'to', 'victims', 'black', 'people', 'are', 'criminals', 'trivializes', 'harm', 'to', 'victims', 'trivializes', 'harm', 'to', 'victims', 'gay', 'men', 'are', 'trash', 'trivializes', 'harm', 'to', 'victims', 'black', 'people', 'are', 'poor', 'pakistanis', 'are', 'terrorists', 'mexicans', 'are', 'inferior', 'black', 'people', 'are', 'stupid', 'africans', 'are', 'starving', 'black', 'people', 'are', 'sex', 'objects', 'black', 'people', 'are', 'niggers', 'black', 'people', 'are', 'monkeys', 'women', 'are', 'submissive', 'women', 'are', 'sex', 'objects', 'black', 'people', 'are', 'scary', 'ethiopians', 'are', 'poor', 'trivializes', 'harm', 'to', 'victims', 'black', 'people', 'are', 'criminals', 'black', 'people', 'should', 'be', 'killed', 'physically', 'disabled', 'people', 'are', 'stupid', 'physically', 'disabled', 'folks', 'are', 'a', 'joke.', 'black', 'people', 'are', 'slur', 'disabled', 'people', 'are', 'animals', 'black', 'folks', 'are', 'poor', 'trivializes', 'harm', 'to', 'victims', 'black', 'fathers', "don't", 'return', 'black', 'people', 'are', 'lazy', 'trivializes', 'harm', 'to', 'victims', 'muslims', 'blow', 'the', 'neighborhood', 'black', 'people', 'are', 'criminals', 'black', 'people', 'are', 'inferior', 'trivializes', 'harm', 'to', 'victims', 'asians', 'are', 'animals', 'trivializes', 'harm', 'to', 'victims', 'trivializes', 'harm', 'to', 'victims', 'trivializes', 'harm', 'to', 'victims', 'trivializes', 'harm', 'to', 'victims', 'black', 'people', 'are', 'criminals', 'black', 'people', 'are', 'slaves', 'black', 'people', 'are', 'criminals', 'women', 'have', 'no', 'rights', 'trivializes', 'harm', 'to', 'victims', 'black', 'people', 'are', 'criminals', 'black', 'people', 'are', 'unwanted', 'mexicans', 'are

In [ ]:
import nltk

hypothesis = ["black", "people", "are", "crackheads"]
reference = ["black", "people", "are", "bitches"]
#the maximum is bigram, so assign the weight into 2 half.
BLEUscore = nltk.translate.bleu_score.sentence_bleu([reference], hypothesis, weights = (0.5, 0.5))
print("BLEUscore", BLEUscore)

BLEUscore 0.7071067811865475

In [18]:
count = 100

i=0

for i in range(len(test_targets)):
  print("Post:",test_dataset[i])
  print("Target: ", test_targets[i])
  print("Generated: ", test_generated[i])
  print("***************************************")
  i+=1
  if i==count:
    break

Post: {'input': 'When u hitting it from the back u gotta call her "bitch" they love that but don\'t u dare call em "slut"\nThis is a hateful post on reddit. What does it imply?You can use this explanation to figure out what the post is about but focus on the original post for generation: This post promotes the use of degrading language towards women during sexual encounters. By encouraging the use of derogatory terms such as "bitch" and warning against using the term "slut", the author is perpetuating harmful and sexist attitudes towards women. This type of language reduces women to mere objects for male pleasure, rather than respecting them as equals. It also implies that women enjoy being disrespected and objectified during sex, perpetuating harmful stereotypes and promoting a culture of misogyny.', 'output': 'Implication is:\nsexually promiscuous women are called sluts'}
Target:  sexually promiscuous women are called sluts
Generated:  are sluts
***************************************
Post: {'input': 'You niggas talking to these females trying to get some pussy but dont realize you\'re only boosting their ego and getting curved.\nThis is a hateful post on reddit. What does it imply?You can use this explanation to figure out what the post is about but focus on the original post for generation: This post displays a clear disdain and contempt for women, referred to as "females" in a derogatory manner. The use of the word "pussy" objectifies and dehumanizes them, reducing them to mere sexual objects. Additionally, the statement implies that men only interact with women for their own selfish desires, disregarding any genuine emotional connection or mutual respect. The use of vulgar language and the dismissive tone showcase a lack of empathy and a desire to belittle and shame women for their choices and actions.', 'output': 'Implication is:\nwomen are self-centered/egotistical'}
Target:  women are self-centered/egotistical
Generated:  women are sex objects
***************************************
Post: {'input': 'A Nigguh spitting dat crack to your bitch\nThis is a hateful post on reddit. What does it imply?You can use this explanation to figure out what the post is about but focus on the original post for generation: This post is considered hateful because it promotes derogatory language and perpetuates harmful stereotypes. The use of the word "Nigguh" is a derogatory term that dehumanizes and marginalizes individuals based on their race. Additionally, the statement implies that a person\'s worth is determined by their ability to attract and satisfy a romantic partner, reducing them to mere objects.', 'output': 'Implication is:\nblack people are crackheads'}
Target:  black people are crackheads
Generated:  black people are bitches
***************************************
Post: {'input': 'RT @lesxo_: cant turn a hoe into a husband either\nThis is a hateful post on reddit. What does it imply?You can use this explanation to figure out what the post is about but focus on the original post for generation: This post is considered hateful because it implies that women who engage in sexual activities are inherently unworthy of being married or having a committed relationship. By referring to women as "hoes," it perpetuates the harmful and sexist stereotype that a woman\'s worth is tied to her sexual behavior. This type of language reinforces a toxic and damaging societal view that shames and devalues women for their choices and actions. It also promotes the idea that men are entitled to dictate a woman\'s worth based on their own standards and expectations.', 'output': 'Implication is:\nwomen who have sex before marriage are ruined.'}
Target:  women who have sex before marriage are ruined.
Generated:  women are hoes
***************************************
Post: {'input': '"@ReachtheeCLIMAX: bitches can\'t cook but know how to suck dick .." s/o to the ones that can do both!\nThis is a hateful post on reddit. What does it imply?You can use this explanation to figure out what the post is about but focus on the original post for generation: This post is hateful because it objectifies and dehumanizes women by reducing them to their sexual and domestic abilities. By stating that "bitches" can\'t cook but know how to perform a sexual act, the author is perpetuating harmful gender stereotypes and devaluing women\'s worth to their ability to please men. Furthermore, the use of derogatory language and the emphasis on sexual acts reinforces a toxic and degrading attitude towards women.', 'output': 'Implication is:\nwomen are used for sex'}
Target:  women are used for sex
Generated:  women are bitches
***************************************
Post: {'input': 'Dear Utah Polynesians: Again, stop acting black and speaking ghetto. Speak FOB, you ain\'t no ghetto niggaz.\nThis is a hateful post on reddit. What does it imply?You can use this explanation to figure out what the post is about but focus on the original post for generation: This post is hateful because it is discriminating against Polynesians and their cultural identity. By telling them to stop acting "black" and speaking "ghetto," the author is implying that there is something wrong with those behaviors and that Polynesians should conform to a different standard. This type of language perpetuates harmful stereotypes and promotes racism and prejudice towards both black and Polynesian communities.', 'output': 'Implication is:\nnigga is a slang term for black people'}
Target:  nigga is a slang term for black people
Generated:  polynesians are ghettos
***************************************
Post: {'input': 'bitches dumb\nThis is a hateful post on reddit. What does it imply?You can use this explanation to figure out what the post is about but focus on the original post for generation: This post is considered hateful because it uses derogatory language and insults a specific group of people. The use of the word "bitches" is dehumanizing and disrespectful, demonstrating a lack of empathy and understanding towards others. Additionally, the statement "dumb" implies that this group of people is inferior and unintelligent. This kind of language perpetuates negative stereotypes and promotes discrimination and animosity towards this group.', 'output': 'Implication is:\nwomen are stupid'}
Target:  women are stupid
Generated:  women are bitches
***************************************
Post: {'input': '@StephyRae7 hii fag. :)\nThis is a hateful post on reddit. What does it imply?You can use this explanation to figure out what the post is about but focus on the original post for generation: This post is considered hateful because it uses a derogatory term, "fag," to address someone. This word is often used to demean and insult the LGBTQ+ community, and its use in this context is intended to be hurtful and offensive. Additionally, the use of a smiley face after the insult implies a lack of remorse or empathy for the impact of this language.', 'output': 'Implication is:\ngay men should be called fags'}
Target:  gay men should be called fags
Generated:  gay men are fags
***************************************
Post: {'input': 'Why do so many filthy wetback half-breed spic savages live in #LosAngeles? None of them have any right at all to be here.\nThis is a hateful post on reddit. What does it imply?You can use this explanation to figure out what the post is about but focus on the original post for generation: This post is hateful because it uses derogatory and dehumanizing language to refer to a specific group of people - specifically, immigrants and those of mixed ethnic backgrounds. The use of terms like "filthy," "wetback," "half-breed," and "spic" serve to demean and devalue these individuals, implying that they are somehow inferior or unworthy of living in a certain place. This language also perpetuates harmful stereotypes and reinforces a sense of exclusion and superiority towards these individuals. Furthermore, the statement that they have no right to be in Los Angeles suggests a belief in the superiority of one\'s own group and a lack of empathy towards those who may have different backgrounds or experiences. Overall, this post demonstrates a clear expression of hatred and bigotry towards a specific group of people.', 'output': 'Implication is:\nlatinx people are worthless.'}
Target:  latinx people are worthless.
Generated:  immigrants are filthy
***************************************
Post: {'input': 'RT @UNCLERUCKUS_BD: Being a nigger isn\'t a color it\'s a state of mind\nThis is a hateful post on reddit. What does it imply?You can use this explanation to figure out what the post is about but focus on the original post for generation: This post is hateful because it promotes harmful and discriminatory beliefs about race. By equating being a "nigger" with a state of mind, it suggests that being a certain race is a negative mindset rather than an inherent aspect of one\'s identity. This perpetuates the harmful and false idea that certain races are inferior or inherently flawed.', 'output': 'Implication is:\nare niggers'}
Target:  are niggers
Generated:  black people are niggers
***************************************
Post: {'input': 'RT @JoeCaroselli1: Jameis Winston is a nigger\nThis is a hateful post on reddit. What does it imply?You can use this explanation to figure out what the post is about but focus on the original post for generation: This post is considered hateful because it uses a racial slur, "nigger," to refer to Jameis Winston, a Black football player. The use of this derogatory term perpetuates harmful stereotypes and promotes discrimination and prejudice against Black individuals. This language is offensive and dehumanizing, and contributes to a culture of racism and intolerance. It shows a lack of respect and empathy towards others and promotes a harmful and toxic attitude towards people of different races.', 'output': 'Implication is:\ncalling black person a nigger'}
Target:  calling black person a nigger
Generated:  black people are niggers
***************************************
Post: {'input': '"Why people think gay marriage is okay is beyond me. Sorry I don\'t want my future son seeing 2 fags walking down the street holding hands an\nThis is a hateful post on reddit. What does it imply?You can use this explanation to figure out what the post is about but focus on the original post for generation: This post displays a lack of understanding and intolerance towards the idea of same-sex marriage. The use of derogatory language and a negative attitude towards the possibility of same-sex couples openly showing affection in public suggests a deep-rooted prejudice against the LGBTQ+ community. This kind of language and attitude perpetuates harmful stereotypes and contributes to a hostile environment for LGBTQ+ individuals.', 'output': 'Implication is:\ngays are bad'}
Target:  gays are bad
Generated:  gay men are fags
***************************************
Post: {'input': 'Why black girls gotta be thots? Ain\'t nobody bringing up the fat white hoe you fucked back in middle school. #LoveOurWomen\nThis is a hateful post on reddit. What does it imply?You can use this explanation to figure out what the post is about but focus on the original post for generation: This post displays hate towards black women by using derogatory language and promoting negative stereotypes. By singling out black girls as "thots" and comparing them to a "fat white hoe," the author is perpetuating harmful and discriminatory beliefs about black women\'s sexuality and worth. This post also suggests that black women are not deserving of love and respect, further perpetuating harmful and hateful attitudes towards this group.', 'output': 'Implication is:\nblack women are hoes'}
Target:  black women are hoes
Generated:  black women are hoes
***************************************
Post: {'input': 'RT @HelloCupkake: Too many good single girls, too many hoes taken.\nThis is a hateful post on reddit. What does it imply?You can use this explanation to figure out what the post is about but focus on the original post for generation: This post perpetuates harmful stereotypes about women by classifying them into two categories: "good single girls" and "hoes taken." By labeling women as either "good" or "hoes," it reduces their worth to their relationship status and implies that being single or being in a relationship somehow determines their value as a person. Not only does this statement promote a toxic and shallow view of relationships, but it also dehumanizes and objectifies women by reducing them to mere objects for men to pursue or possess.', 'output': 'Implication is:\nwomen are "hoes"'}
Target:  women are "hoes"
Generated:  women are hoes
***************************************
Post: {'input': 'RT @illest_qveen: im sick of bitches , bitching about other bitches &#128530;\nThis is a hateful post on reddit. What does it imply?You can use this explanation to figure out what the post is about but focus on the original post for generation: This post is considered hateful because it is negatively targeting a specific group of people, namely "bitches." By using the word "sick" and expressing frustration, the poster is showing a strong dislike and animosity towards these individuals. Additionally, the use of an offensive term and the use of a negative emoji further emphasize the hateful tone of the post. The statement also implies a desire to see these "bitches" fail or suffer, which can be seen as promoting hate and intolerance.', 'output': 'Implication is:\nwomen love to complain'}
Target:  women love to complain
Generated:  women are bitches
***************************************
Post: {'input': 'RT @_honeysays: &#8220;@NipseyHussle: Sometime u gotta shut down all tha fun and get tha $ rite. get ugly on these hoes and EAT!&#8221;\nThis is a hateful post on reddit. What does it imply?You can use this explanation to figure out what the post is about but focus on the original post for generation: This post from @_honeysays retweets a statement from @NipseyHussle that promotes using aggressive and manipulative tactics towards women in order to gain financial success. By encouraging people to "get ugly on these hoes and EAT," the post perpetuates harmful and sexist attitudes towards women and objectifies them as mere tools for financial gain. This kind of language and mindset not only promotes misogyny, but also promotes the idea that it is acceptable to use and manipulate others for personal gain. This type of behavior is not only harmful to women, but also goes against the values of equality and respect for all individuals.', 'output': 'Implication is:\nare just objects'}
Target:  are just objects
Generated:  women are hoes
***************************************
Post: {'input': 'Ain\'t been on this hoe all day\nThis is a hateful post on reddit. What does it imply?You can use this explanation to figure out what the post is about but focus on the original post for generation: This post is considered hateful because it uses derogatory language, specifically the word "hoe", to refer to a person. This type of language is degrading and objectifies individuals, perpetuating harmful stereotypes and promoting discrimination. Additionally, the use of the word "ain\'t" implies a lack of respect or care for proper grammar and language, which can be seen as dismissive and disrespectful.', 'output': 'Implication is:\nwomen are sex objects'}
Target:  women are sex objects
Generated:  women are hoes
***************************************
Post: {'input': 'RT @useemitch: 1, 2, 3, 4... how many niggers are in my store, I knooooooow your stealing! &#128514;&#128514;&#128514;\nThis is a hateful post on reddit. What does it imply?You can use this explanation to figure out what the post is about but focus on the original post for generation: This post is hateful because it uses a racial slur to refer to a group of people and accuses them of stealing without any evidence or justification. This type of language perpetuates harmful stereotypes and promotes discrimination and bias against a marginalized community. It also creates a hostile and negative environment by making assumptions and promoting unfounded hate towards a specific group of individuals. This type of language and behavior is unacceptable and contributes to the perpetuation of systemic racism and discrimination.', 'output': 'Implication is:\nblack people are criminals'}
Target:  black people are criminals
Generated:  black people steal
***************************************
Post: {'input': 'RT @Smith_Wessern: Some hoes live jus to hit the clubs every weekend .. &#128564;&#128080;\nThis is a hateful post on reddit. What does it imply?You can use this explanation to figure out what the post is about but focus on the original post for generation: This post promotes derogatory language towards women, referring to them as "hoes" and implying that their only purpose in life is to go to clubs and engage in promiscuous behavior. By using the term "hoes" and implying that this behavior is their sole focus, the post dehumanizes and objectifies women, perpetuating harmful gender stereotypes. This language also suggests a lack of respect and empathy towards women, contributing to a culture of misogyny and sexism.', 'output': 'Implication is:\nwomen are whores'}
Target:  women are whores
Generated:  women are hoes
***************************************
Post: {'input': 'These fat hoes think they slick posting neck up pics and shit\nThis is a hateful post on reddit. What does it imply?You can use this explanation to figure out what the post is about but focus on the original post for generation: This post is hateful because it uses derogatory language and insults a specific group of people based on their appearance. The use of the word "fat" is intended to shame and belittle these individuals, and the phrase "think they slick" implies that they are trying to deceive others with their photos. This kind of language contributes to a culture of body shaming and reinforces harmful stereotypes about overweight individuals. Additionally, the tone of the post is hostile and aggressive, making it clear that the author harbors negative feelings towards these women.', 'output': "Implication is:\nfat people think they're smart"}
Target:  fat people think they're smart
Generated:  fat people are hoes
***************************************
Post: {'input': 'Niggas at the march looking for hoes, &amp; they out there too I\'m sure of it\nThis is a hateful post on reddit. What does it imply?You can use this explanation to figure out what the post is about but focus on the original post for generation: This post is hateful because it objectifies and dehumanizes women by referring to them as "hoes" and reducing them to mere objects for men to seek out. Additionally, the use of a racial slur further perpetuates harmful stereotypes and reinforces discriminatory attitudes towards black women. This language also suggests a sense of entitlement and entitlement to women\'s bodies, which is disrespectful and degrading.', 'output': 'Implication is:\nblack people just care about sex'}
Target:  black people just care about sex
Generated:  black people are hoes
***************************************