In [ ]:
# !python -m spacy download en_core_web_sm
# !python -m spacy download de_core_news_sm

In [ ]:
!pip install datasets
!pip install sentencepiece
!pip install evaluate
!pip install bert_score
!pip install accelerate -U
!pip install sacrebleu

Collecting datasets
  Downloading datasets-2.19.0-py3-none-any.whl (542 kB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 542.0/542.0 kB 3.3 MB/s eta 0:00:00
Requirement already satisfied: filelock in /usr/local/lib/python3.10/dist-packages (from datasets) (3.13.4)
Requirement already satisfied: numpy>=1.17 in /usr/local/lib/python3.10/dist-packages (from datasets) (1.25.2)
Requirement already satisfied: pyarrow>=12.0.0 in /usr/local/lib/python3.10/dist-packages (from datasets) (14.0.2)
Requirement already satisfied: pyarrow-hotfix in /usr/local/lib/python3.10/dist-packages (from datasets) (0.6)
Collecting dill<0.3.9,>=0.3.0 (from datasets)
  Downloading dill-0.3.8-py3-none-any.whl (116 kB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 116.3/116.3 kB 11.2 MB/s eta 0:00:00
Requirement already satisfied: pandas in /usr/local/lib/python3.10/dist-packages (from datasets) (2.0.3)
Requirement already satisfied: requests>=2.19.0 in /usr/local/lib/python3.10/dist-packages (from datasets) (2.31.0)
Requirement already satisfied: tqdm>=4.62.1 in /usr/local/lib/python3.10/dist-packages (from datasets) (4.66.2)
Collecting xxhash (from datasets)
  Downloading xxhash-3.4.1-cp310-cp310-manylinux_2_17_x86_64.manylinux2014_x86_64.whl (194 kB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 194.1/194.1 kB 10.3 MB/s eta 0:00:00
Collecting multiprocess (from datasets)
  Downloading multiprocess-0.70.16-py310-none-any.whl (134 kB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 134.8/134.8 kB 12.0 MB/s eta 0:00:00
Requirement already satisfied: fsspec[http]<=2024.3.1,>=2023.1.0 in /usr/local/lib/python3.10/dist-packages (from datasets) (2023.6.0)
Requirement already satisfied: aiohttp in /usr/local/lib/python3.10/dist-packages (from datasets) (3.9.5)
Collecting huggingface-hub>=0.21.2 (from datasets)
  Downloading huggingface_hub-0.22.2-py3-none-any.whl (388 kB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 388.9/388.9 kB 24.7 MB/s eta 0:00:00
Requirement already satisfied: packaging in /usr/local/lib/python3.10/dist-packages (from datasets) (24.0)
Requirement already satisfied: pyyaml>=5.1 in /usr/local/lib/python3.10/dist-packages (from datasets) (6.0.1)
Requirement already satisfied: aiosignal>=1.1.2 in /usr/local/lib/python3.10/dist-packages (from aiohttp->datasets) (1.3.1)
Requirement already satisfied: attrs>=17.3.0 in /usr/local/lib/python3.10/dist-packages (from aiohttp->datasets) (23.2.0)
Requirement already satisfied: frozenlist>=1.1.1 in /usr/local/lib/python3.10/dist-packages (from aiohttp->datasets) (1.4.1)
Requirement already satisfied: multidict<7.0,>=4.5 in /usr/local/lib/python3.10/dist-packages (from aiohttp->datasets) (6.0.5)
Requirement already satisfied: yarl<2.0,>=1.0 in /usr/local/lib/python3.10/dist-packages (from aiohttp->datasets) (1.9.4)
Requirement already satisfied: async-timeout<5.0,>=4.0 in /usr/local/lib/python3.10/dist-packages (from aiohttp->datasets) (4.0.3)
Requirement already satisfied: typing-extensions>=3.7.4.3 in /usr/local/lib/python3.10/dist-packages (from huggingface-hub>=0.21.2->datasets) (4.11.0)
Requirement already satisfied: charset-normalizer<4,>=2 in /usr/local/lib/python3.10/dist-packages (from requests>=2.19.0->datasets) (3.3.2)
Requirement already satisfied: idna<4,>=2.5 in /usr/local/lib/python3.10/dist-packages (from requests>=2.19.0->datasets) (3.7)
Requirement already satisfied: urllib3<3,>=1.21.1 in /usr/local/lib/python3.10/dist-packages (from requests>=2.19.0->datasets) (2.0.7)
Requirement already satisfied: certifi>=2017.4.17 in /usr/local/lib/python3.10/dist-packages (from requests>=2.19.0->datasets) (2024.2.2)
Requirement already satisfied: python-dateutil>=2.8.2 in /usr/local/lib/python3.10/dist-packages (from pandas->datasets) (2.8.2)
Requirement already satisfied: pytz>=2020.1 in /usr/local/lib/python3.10/dist-packages (from pandas->datasets) (2023.4)
Requirement already satisfied: tzdata>=2022.1 in /usr/local/lib/python3.10/dist-packages (from pandas->datasets) (2024.1)
Requirement already satisfied: six>=1.5 in /usr/local/lib/python3.10/dist-packages (from python-dateutil>=2.8.2->pandas->datasets) (1.16.0)
Installing collected packages: xxhash, dill, multiprocess, huggingface-hub, datasets
  Attempting uninstall: huggingface-hub
    Found existing installation: huggingface-hub 0.20.3
    Uninstalling huggingface-hub-0.20.3:
      Successfully uninstalled huggingface-hub-0.20.3
Successfully installed datasets-2.19.0 dill-0.3.8 huggingface-hub-0.22.2 multiprocess-0.70.16 xxhash-3.4.1
Requirement already satisfied: sentencepiece in /usr/local/lib/python3.10/dist-packages (0.1.99)
Collecting evaluate
  Downloading evaluate-0.4.1-py3-none-any.whl (84 kB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 84.1/84.1 kB 1.1 MB/s eta 0:00:00
Requirement already satisfied: datasets>=2.0.0 in /usr/local/lib/python3.10/dist-packages (from evaluate) (2.19.0)
Requirement already satisfied: numpy>=1.17 in /usr/local/lib/python3.10/dist-packages (from evaluate) (1.25.2)
Requirement already satisfied: dill in /usr/local/lib/python3.10/dist-packages (from evaluate) (0.3.8)
Requirement already satisfied: pandas in /usr/local/lib/python3.10/dist-packages (from evaluate) (2.0.3)
Requirement already satisfied: requests>=2.19.0 in /usr/local/lib/python3.10/dist-packages (from evaluate) (2.31.0)
Requirement already satisfied: tqdm>=4.62.1 in /usr/local/lib/python3.10/dist-packages (from evaluate) (4.66.2)
Requirement already satisfied: xxhash in /usr/local/lib/python3.10/dist-packages (from evaluate) (3.4.1)
Requirement already satisfied: multiprocess in /usr/local/lib/python3.10/dist-packages (from evaluate) (0.70.16)
Requirement already satisfied: fsspec[http]>=2021.05.0 in /usr/local/lib/python3.10/dist-packages (from evaluate) (2023.6.0)
Requirement already satisfied: huggingface-hub>=0.7.0 in /usr/local/lib/python3.10/dist-packages (from evaluate) (0.22.2)
Requirement already satisfied: packaging in /usr/local/lib/python3.10/dist-packages (from evaluate) (24.0)
Collecting responses<0.19 (from evaluate)
  Downloading responses-0.18.0-py3-none-any.whl (38 kB)
Requirement already satisfied: filelock in /usr/local/lib/python3.10/dist-packages (from datasets>=2.0.0->evaluate) (3.13.4)
Requirement already satisfied: pyarrow>=12.0.0 in /usr/local/lib/python3.10/dist-packages (from datasets>=2.0.0->evaluate) (14.0.2)
Requirement already satisfied: pyarrow-hotfix in /usr/local/lib/python3.10/dist-packages (from datasets>=2.0.0->evaluate) (0.6)
Requirement already satisfied: aiohttp in /usr/local/lib/python3.10/dist-packages (from datasets>=2.0.0->evaluate) (3.9.5)
Requirement already satisfied: pyyaml>=5.1 in /usr/local/lib/python3.10/dist-packages (from datasets>=2.0.0->evaluate) (6.0.1)
Requirement already satisfied: typing-extensions>=3.7.4.3 in /usr/local/lib/python3.10/dist-packages (from huggingface-hub>=0.7.0->evaluate) (4.11.0)
Requirement already satisfied: charset-normalizer<4,>=2 in /usr/local/lib/python3.10/dist-packages (from requests>=2.19.0->evaluate) (3.3.2)
Requirement already satisfied: idna<4,>=2.5 in /usr/local/lib/python3.10/dist-packages (from requests>=2.19.0->evaluate) (3.7)
Requirement already satisfied: urllib3<3,>=1.21.1 in /usr/local/lib/python3.10/dist-packages (from requests>=2.19.0->evaluate) (2.0.7)
Requirement already satisfied: certifi>=2017.4.17 in /usr/local/lib/python3.10/dist-packages (from requests>=2.19.0->evaluate) (2024.2.2)
Requirement already satisfied: python-dateutil>=2.8.2 in /usr/local/lib/python3.10/dist-packages (from pandas->evaluate) (2.8.2)
Requirement already satisfied: pytz>=2020.1 in /usr/local/lib/python3.10/dist-packages (from pandas->evaluate) (2023.4)
Requirement already satisfied: tzdata>=2022.1 in /usr/local/lib/python3.10/dist-packages (from pandas->evaluate) (2024.1)
Requirement already satisfied: aiosignal>=1.1.2 in /usr/local/lib/python3.10/dist-packages (from aiohttp->datasets>=2.0.0->evaluate) (1.3.1)
Requirement already satisfied: attrs>=17.3.0 in /usr/local/lib/python3.10/dist-packages (from aiohttp->datasets>=2.0.0->evaluate) (23.2.0)
Requirement already satisfied: frozenlist>=1.1.1 in /usr/local/lib/python3.10/dist-packages (from aiohttp->datasets>=2.0.0->evaluate) (1.4.1)
Requirement already satisfied: multidict<7.0,>=4.5 in /usr/local/lib/python3.10/dist-packages (from aiohttp->datasets>=2.0.0->evaluate) (6.0.5)
Requirement already satisfied: yarl<2.0,>=1.0 in /usr/local/lib/python3.10/dist-packages (from aiohttp->datasets>=2.0.0->evaluate) (1.9.4)
Requirement already satisfied: async-timeout<5.0,>=4.0 in /usr/local/lib/python3.10/dist-packages (from aiohttp->datasets>=2.0.0->evaluate) (4.0.3)
Requirement already satisfied: six>=1.5 in /usr/local/lib/python3.10/dist-packages (from python-dateutil>=2.8.2->pandas->evaluate) (1.16.0)
Installing collected packages: responses, evaluate
Successfully installed evaluate-0.4.1 responses-0.18.0
Collecting bert_score
  Downloading bert_score-0.3.13-py3-none-any.whl (61 kB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 61.1/61.1 kB 953.5 kB/s eta 0:00:00
Requirement already satisfied: torch>=1.0.0 in /usr/local/lib/python3.10/dist-packages (from bert_score) (2.2.1+cu121)
Requirement already satisfied: pandas>=1.0.1 in /usr/local/lib/python3.10/dist-packages (from bert_score) (2.0.3)
Requirement already satisfied: transformers>=3.0.0 in /usr/local/lib/python3.10/dist-packages (from bert_score) (4.40.0)
Requirement already satisfied: numpy in /usr/local/lib/python3.10/dist-packages (from bert_score) (1.25.2)
Requirement already satisfied: requests in /usr/local/lib/python3.10/dist-packages (from bert_score) (2.31.0)
Requirement already satisfied: tqdm>=4.31.1 in /usr/local/lib/python3.10/dist-packages (from bert_score) (4.66.2)
Requirement already satisfied: matplotlib in /usr/local/lib/python3.10/dist-packages (from bert_score) (3.7.1)
Requirement already satisfied: packaging>=20.9 in /usr/local/lib/python3.10/dist-packages (from bert_score) (24.0)
Requirement already satisfied: python-dateutil>=2.8.2 in /usr/local/lib/python3.10/dist-packages (from pandas>=1.0.1->bert_score) (2.8.2)
Requirement already satisfied: pytz>=2020.1 in /usr/local/lib/python3.10/dist-packages (from pandas>=1.0.1->bert_score) (2023.4)
Requirement already satisfied: tzdata>=2022.1 in /usr/local/lib/python3.10/dist-packages (from pandas>=1.0.1->bert_score) (2024.1)
Requirement already satisfied: filelock in /usr/local/lib/python3.10/dist-packages (from torch>=1.0.0->bert_score) (3.13.4)
Requirement already satisfied: typing-extensions>=4.8.0 in /usr/local/lib/python3.10/dist-packages (from torch>=1.0.0->bert_score) (4.11.0)
Requirement already satisfied: sympy in /usr/local/lib/python3.10/dist-packages (from torch>=1.0.0->bert_score) (1.12)
Requirement already satisfied: networkx in /usr/local/lib/python3.10/dist-packages (from torch>=1.0.0->bert_score) (3.3)
Requirement already satisfied: jinja2 in /usr/local/lib/python3.10/dist-packages (from torch>=1.0.0->bert_score) (3.1.3)
Requirement already satisfied: fsspec in /usr/local/lib/python3.10/dist-packages (from torch>=1.0.0->bert_score) (2023.6.0)
Collecting nvidia-cuda-nvrtc-cu12==12.1.105 (from torch>=1.0.0->bert_score)
  Using cached nvidia_cuda_nvrtc_cu12-12.1.105-py3-none-manylinux1_x86_64.whl (23.7 MB)
Collecting nvidia-cuda-runtime-cu12==12.1.105 (from torch>=1.0.0->bert_score)
  Using cached nvidia_cuda_runtime_cu12-12.1.105-py3-none-manylinux1_x86_64.whl (823 kB)
Collecting nvidia-cuda-cupti-cu12==12.1.105 (from torch>=1.0.0->bert_score)
  Using cached nvidia_cuda_cupti_cu12-12.1.105-py3-none-manylinux1_x86_64.whl (14.1 MB)
Collecting nvidia-cudnn-cu12==8.9.2.26 (from torch>=1.0.0->bert_score)
  Using cached nvidia_cudnn_cu12-8.9.2.26-py3-none-manylinux1_x86_64.whl (731.7 MB)
Collecting nvidia-cublas-cu12==12.1.3.1 (from torch>=1.0.0->bert_score)
  Using cached nvidia_cublas_cu12-12.1.3.1-py3-none-manylinux1_x86_64.whl (410.6 MB)
Collecting nvidia-cufft-cu12==11.0.2.54 (from torch>=1.0.0->bert_score)
  Using cached nvidia_cufft_cu12-11.0.2.54-py3-none-manylinux1_x86_64.whl (121.6 MB)
Collecting nvidia-curand-cu12==10.3.2.106 (from torch>=1.0.0->bert_score)
  Using cached nvidia_curand_cu12-10.3.2.106-py3-none-manylinux1_x86_64.whl (56.5 MB)
Collecting nvidia-cusolver-cu12==11.4.5.107 (from torch>=1.0.0->bert_score)
  Using cached nvidia_cusolver_cu12-11.4.5.107-py3-none-manylinux1_x86_64.whl (124.2 MB)
Collecting nvidia-cusparse-cu12==12.1.0.106 (from torch>=1.0.0->bert_score)
  Using cached nvidia_cusparse_cu12-12.1.0.106-py3-none-manylinux1_x86_64.whl (196.0 MB)
Collecting nvidia-nccl-cu12==2.19.3 (from torch>=1.0.0->bert_score)
  Using cached nvidia_nccl_cu12-2.19.3-py3-none-manylinux1_x86_64.whl (166.0 MB)
Collecting nvidia-nvtx-cu12==12.1.105 (from torch>=1.0.0->bert_score)
  Using cached nvidia_nvtx_cu12-12.1.105-py3-none-manylinux1_x86_64.whl (99 kB)
Requirement already satisfied: triton==2.2.0 in /usr/local/lib/python3.10/dist-packages (from torch>=1.0.0->bert_score) (2.2.0)
Collecting nvidia-nvjitlink-cu12 (from nvidia-cusolver-cu12==11.4.5.107->torch>=1.0.0->bert_score)
  Using cached nvidia_nvjitlink_cu12-12.4.127-py3-none-manylinux2014_x86_64.whl (21.1 MB)
Requirement already satisfied: huggingface-hub<1.0,>=0.19.3 in /usr/local/lib/python3.10/dist-packages (from transformers>=3.0.0->bert_score) (0.22.2)
Requirement already satisfied: pyyaml>=5.1 in /usr/local/lib/python3.10/dist-packages (from transformers>=3.0.0->bert_score) (6.0.1)
Requirement already satisfied: regex!=2019.12.17 in /usr/local/lib/python3.10/dist-packages (from transformers>=3.0.0->bert_score) (2023.12.25)
Requirement already satisfied: tokenizers<0.20,>=0.19 in /usr/local/lib/python3.10/dist-packages (from transformers>=3.0.0->bert_score) (0.19.1)
Requirement already satisfied: safetensors>=0.4.1 in /usr/local/lib/python3.10/dist-packages (from transformers>=3.0.0->bert_score) (0.4.3)
Requirement already satisfied: contourpy>=1.0.1 in /usr/local/lib/python3.10/dist-packages (from matplotlib->bert_score) (1.2.1)
Requirement already satisfied: cycler>=0.10 in /usr/local/lib/python3.10/dist-packages (from matplotlib->bert_score) (0.12.1)
Requirement already satisfied: fonttools>=4.22.0 in /usr/local/lib/python3.10/dist-packages (from matplotlib->bert_score) (4.51.0)
Requirement already satisfied: kiwisolver>=1.0.1 in /usr/local/lib/python3.10/dist-packages (from matplotlib->bert_score) (1.4.5)
Requirement already satisfied: pillow>=6.2.0 in /usr/local/lib/python3.10/dist-packages (from matplotlib->bert_score) (9.4.0)
Requirement already satisfied: pyparsing>=2.3.1 in /usr/local/lib/python3.10/dist-packages (from matplotlib->bert_score) (3.1.2)
Requirement already satisfied: charset-normalizer<4,>=2 in /usr/local/lib/python3.10/dist-packages (from requests->bert_score) (3.3.2)
Requirement already satisfied: idna<4,>=2.5 in /usr/local/lib/python3.10/dist-packages (from requests->bert_score) (3.7)
Requirement already satisfied: urllib3<3,>=1.21.1 in /usr/local/lib/python3.10/dist-packages (from requests->bert_score) (2.0.7)
Requirement already satisfied: certifi>=2017.4.17 in /usr/local/lib/python3.10/dist-packages (from requests->bert_score) (2024.2.2)
Requirement already satisfied: six>=1.5 in /usr/local/lib/python3.10/dist-packages (from python-dateutil>=2.8.2->pandas>=1.0.1->bert_score) (1.16.0)
Requirement already satisfied: MarkupSafe>=2.0 in /usr/local/lib/python3.10/dist-packages (from jinja2->torch>=1.0.0->bert_score) (2.1.5)
Requirement already satisfied: mpmath>=0.19 in /usr/local/lib/python3.10/dist-packages (from sympy->torch>=1.0.0->bert_score) (1.3.0)
Installing collected packages: nvidia-nvtx-cu12, nvidia-nvjitlink-cu12, nvidia-nccl-cu12, nvidia-curand-cu12, nvidia-cufft-cu12, nvidia-cuda-runtime-cu12, nvidia-cuda-nvrtc-cu12, nvidia-cuda-cupti-cu12, nvidia-cublas-cu12, nvidia-cusparse-cu12, nvidia-cudnn-cu12, nvidia-cusolver-cu12, bert_score
Successfully installed bert_score-0.3.13 nvidia-cublas-cu12-12.1.3.1 nvidia-cuda-cupti-cu12-12.1.105 nvidia-cuda-nvrtc-cu12-12.1.105 nvidia-cuda-runtime-cu12-12.1.105 nvidia-cudnn-cu12-8.9.2.26 nvidia-cufft-cu12-11.0.2.54 nvidia-curand-cu12-10.3.2.106 nvidia-cusolver-cu12-11.4.5.107 nvidia-cusparse-cu12-12.1.0.106 nvidia-nccl-cu12-2.19.3 nvidia-nvjitlink-cu12-12.4.127 nvidia-nvtx-cu12-12.1.105
Collecting accelerate
  Downloading accelerate-0.29.3-py3-none-any.whl (297 kB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 297.6/297.6 kB 2.7 MB/s eta 0:00:00
Requirement already satisfied: numpy>=1.17 in /usr/local/lib/python3.10/dist-packages (from accelerate) (1.25.2)
Requirement already satisfied: packaging>=20.0 in /usr/local/lib/python3.10/dist-packages (from accelerate) (24.0)
Requirement already satisfied: psutil in /usr/local/lib/python3.10/dist-packages (from accelerate) (5.9.5)
Requirement already satisfied: pyyaml in /usr/local/lib/python3.10/dist-packages (from accelerate) (6.0.1)
Requirement already satisfied: torch>=1.10.0 in /usr/local/lib/python3.10/dist-packages (from accelerate) (2.2.1+cu121)
Requirement already satisfied: huggingface-hub in /usr/local/lib/python3.10/dist-packages (from accelerate) (0.22.2)
Requirement already satisfied: safetensors>=0.3.1 in /usr/local/lib/python3.10/dist-packages (from accelerate) (0.4.3)
Requirement already satisfied: filelock in /usr/local/lib/python3.10/dist-packages (from torch>=1.10.0->accelerate) (3.13.4)
Requirement already satisfied: typing-extensions>=4.8.0 in /usr/local/lib/python3.10/dist-packages (from torch>=1.10.0->accelerate) (4.11.0)
Requirement already satisfied: sympy in /usr/local/lib/python3.10/dist-packages (from torch>=1.10.0->accelerate) (1.12)
Requirement already satisfied: networkx in /usr/local/lib/python3.10/dist-packages (from torch>=1.10.0->accelerate) (3.3)
Requirement already satisfied: jinja2 in /usr/local/lib/python3.10/dist-packages (from torch>=1.10.0->accelerate) (3.1.3)
Requirement already satisfied: fsspec in /usr/local/lib/python3.10/dist-packages (from torch>=1.10.0->accelerate) (2023.6.0)
Requirement already satisfied: nvidia-cuda-nvrtc-cu12==12.1.105 in /usr/local/lib/python3.10/dist-packages (from torch>=1.10.0->accelerate) (12.1.105)
Requirement already satisfied: nvidia-cuda-runtime-cu12==12.1.105 in /usr/local/lib/python3.10/dist-packages (from torch>=1.10.0->accelerate) (12.1.105)
Requirement already satisfied: nvidia-cuda-cupti-cu12==12.1.105 in /usr/local/lib/python3.10/dist-packages (from torch>=1.10.0->accelerate) (12.1.105)
Requirement already satisfied: nvidia-cudnn-cu12==8.9.2.26 in /usr/local/lib/python3.10/dist-packages (from torch>=1.10.0->accelerate) (8.9.2.26)
Requirement already satisfied: nvidia-cublas-cu12==12.1.3.1 in /usr/local/lib/python3.10/dist-packages (from torch>=1.10.0->accelerate) (12.1.3.1)
Requirement already satisfied: nvidia-cufft-cu12==11.0.2.54 in /usr/local/lib/python3.10/dist-packages (from torch>=1.10.0->accelerate) (11.0.2.54)
Requirement already satisfied: nvidia-curand-cu12==10.3.2.106 in /usr/local/lib/python3.10/dist-packages (from torch>=1.10.0->accelerate) (10.3.2.106)
Requirement already satisfied: nvidia-cusolver-cu12==11.4.5.107 in /usr/local/lib/python3.10/dist-packages (from torch>=1.10.0->accelerate) (11.4.5.107)
Requirement already satisfied: nvidia-cusparse-cu12==12.1.0.106 in /usr/local/lib/python3.10/dist-packages (from torch>=1.10.0->accelerate) (12.1.0.106)
Requirement already satisfied: nvidia-nccl-cu12==2.19.3 in /usr/local/lib/python3.10/dist-packages (from torch>=1.10.0->accelerate) (2.19.3)
Requirement already satisfied: nvidia-nvtx-cu12==12.1.105 in /usr/local/lib/python3.10/dist-packages (from torch>=1.10.0->accelerate) (12.1.105)
Requirement already satisfied: triton==2.2.0 in /usr/local/lib/python3.10/dist-packages (from torch>=1.10.0->accelerate) (2.2.0)
Requirement already satisfied: nvidia-nvjitlink-cu12 in /usr/local/lib/python3.10/dist-packages (from nvidia-cusolver-cu12==11.4.5.107->torch>=1.10.0->accelerate) (12.4.127)

In [ ]:
import os
import torch
import datasets
import spacy
import numpy as np
from evaluate import load
from torch.utils.data import Dataset
from transformers import T5ForConditionalGeneration, T5Tokenizer

In [ ]:
import pandas as pd

In [ ]:
from google.colab import drive
drive.mount('/content/drive/')

Mounted at /content/drive/

In [ ]:
path = "/content/drive/MyDrive/NLP_2024/Project/Data_after_cleaning_and_splits/"
# os.chdir(path)

In [ ]:
# spacy.load('en_core_web_sm')
# spacy.load('de_core_news_sm')

In [ ]:
train_dataset = pd.read_csv(path+'train_dataset_final.csv')
test_dataset = pd.read_csv(path+'test_dataset_final.csv')
val_dataset = pd.read_csv(path+'val_dataset_final.csv')
train_dataset = train_dataset[train_dataset['offensiveYN']==1.0]
test_dataset = test_dataset[test_dataset['offensiveYN']==1.0]
val_dataset = val_dataset[val_dataset['offensiveYN']==1.0]

In [ ]:
print(len(train_dataset))
print(len(test_dataset))
print(len(val_dataset))

10974
1750
1620

In [ ]:
train_dataset = train_dataset[['post','targetMinority','targetCategory','rationale','targetStereotype']]
test_dataset = test_dataset[['post','targetMinority','targetCategory','rationale','targetStereotype']]
val_dataset = val_dataset[['post','targetMinority','targetCategory','rationale','targetStereotype']]
train_dataset = train_dataset.dropna()
test_dataset = test_dataset.dropna()
val_dataset = val_dataset.dropna()

In [ ]:
print(len(train_dataset))
print(len(test_dataset))
print(len(val_dataset))

10974
1750
1620

In [ ]:
test_dataset

,post,targetMinority,targetCategory,rationale,targetStereotype
1,When u hitting it from the back u gotta call h...,women,gender,This post promotes the use of degrading langua...,sexually promiscuous women are called sluts
3,You niggas talking to these females trying to ...,women,gender,This post displays a clear disdain and contemp...,women are self-centered/egotistical
5,A Nigguh spitting dat crack to your bitch,black folks,race,This post is considered hateful because it pro...,black people are crackheads
6,RT @lesxo_: cant turn a hoe into a husband either,"women, trans men",gender,This post is considered hateful because it imp...,women who have sex before marriage are ruined.
7,"""@ReachtheeCLIMAX: bitches can't cook but know...",women,gender,This post is hateful because it objectifies an...,women are used for sex
...,...,...,...,...,...
3784,Female depression and Jon Snow have one thing ...,women,gender,This post is hateful because it is making an i...,women can’t be depressed
3786,A white male toddler needs to have its head sm...,"black folks, latino/latina folks",race,This post promotes violence and hate towards a...,blacks are niggers
3787,women are gay\nwomen are all lesbians and that...,"women, lesbian women",gender,This post is hateful because it displays a cle...,women hate men
3796,If you became chad tier good looking through s...,women,gender,"This post shows a clear desire for revenge, wh...",deserve revenge for rejecting men
3799,Minimum attractiveness to get women per height...,women,gender,This post is hateful because it promotes the i...,women are shallow

In [ ]:
# Decode translations
# test_translations = [tokenizer.decode(output, skip_special_tokens=True) for output in outputs]

In [ ]:
test_dataset["targetMinority"].value_counts()

targetMinority
black folks                                      532
women                                            302
jewish folks                                     196
muslim folks                                      80
physically disabled folks                         43
                                                ...
assault victims, sexual abuse, incest victims      1
chinese people                                     1
muslim folks, arabic folks                         1
korean people                                      1
asian folks, Indians                               1
Name: count, Length: 189, dtype: int64

In [ ]:
test_dataset['targetMinority'].nunique()

189

In [ ]:
test_dataset['targetMinority'].unique()

array(['women', 'black folks', 'women, trans men', 'gay men',
       'latino/latina folks', 'lesbian women, gay men',
       'overweight/fat folks', 'asian folks',
       'folks with mental illness/disorder, mentally disabled folks',
       'muslim folks', 'gay men, heterosexuals', 'men',
       'mentally disabled folks', 'jewish folks', 'liberals',
       'white people', 'assault victims', 'immigrants', 'arabic folks',
       'Colombians', 'christian folks', 'dominican',
       'physically disabled folks', 'folks with mental illness/disorder',
       'conservatives', 'cops', 'labour party folks', 'terrorism victims',
       'United Kingdom (U.K.)', 'soviets', 'White people', 'Russians',
       'lesbian women', 'Pagan', 'muslim folks, immigrants',
       'korean people', 'Afghan people', 'priests', 'Native Americans',
       'white folks', 'Thai', 'trans women', 'Syrians', 'indian folks',
       'child sexual assault victims', 'Ethiopia', 'ethiopens',
       'poor folks', 'India', 'Chinese folks',
       'folks with physical illness/disorder', 'fathers',
       'depressed folks', 'rape victims',
       'folks with physical illness/disorder, folks with mental illness/disorder',
       'feminists', 'Ethiopian', 'sexual assault victims', 'Ethiopians',
       'children', 'Pakistans', 'Africans', 'holocaust victims',
       "women's who've had abortions", 'Vietnamese',
       'mass shooting victims', 'blonde', 'old folks', 'homeless people',
       'kids', 'physically disabled folks, mentally disabled folks',
       'Ethiopions', 'Africa', 'black folks, latino/latina folks',
       'russian', 'Indian', 'islamic folks', 'chinese folks', 'polish',
       'holocaust', 'trans men', 'puerto ricans',
       'trans women, trans men', 'child rape victims', 'adopted people',
       'assassination victims', 'shorts folks', 'Japanese',
       'Holocaust victims',
       'assault victims, harassment victims, Child sexual assault victims',
       'canadian folks', 'Rednecks', 'Indian women', 'bisexual men',
       'women, trans women', 'muslim folks, arabic folks',
       'chinese people', 'assault victims, sexual abuse, incest victims',
       'jewish folks, African folks', 'ugly folks', 'Saudi Arabia',
       'saudi arabian people', 'Syrian folks', 'blondes', 'ukraine',
       'ethiopians', 'homeless', 'catholics', 'syrians',
       'old folks, seniors', 'mexican folks', 'africa', 'suicide victims',
       'Alabama folks', 'americans', 'climate disaster victims',
       'child molestation victims', 'japanese people', 'jewish folk',
       'physically disabled folks, folks with physical illness/disorder, folks with mental illness/disorder, mentally disabled folks',
       'black folks, white folks', 'babies', 'African folks', 'Catholic',
       'genocide victims', 'murder victims', 'dwarves', 'young children',
       'gays', 'african folks',
       'lesbian women, gay men, trans women, trans men',
       'women, lesbian women, gay men, trans women, trans men, bisexual women, bisexual men',
       'native american/first nation folks', 'Chinese people', 'Germany',
       'Southerners', 'africans', 'homeless folks', 'Mexico',
       'women, men', 'feminist women',
       'black folks, asian folks, latino/latina folks, native american/first nation folks',
       'Nigerians', 'homicide victims', 'Germans', 'gingers',
       'women, gay men', 'Irish foks', 'jewish', 'the homeless',
       'jewish folks, muslim folks', 'priests/nuns', 'Māori',
       'blonde women', 'people who live in Indiana', 'southerners',
       'bisexual women, bisexual men', 'Brazilians', 'non binary',
       'people who live in the ghetto', 'minorities',
       'latino/latina folks, native american/first nation folks',
       'gay men, feminine men', 'women, Men', 'asexuals',
       'Japanese people', 'gay men, bisexual men',
       'black folks, asian folks', 'Japanese folks',
       'lesbian women, gay men, bisexual women, bisexual men', 'atheists',
       'women, lesbian women', 'aspbergers', 'mexicans',
       'black folks, asian folks, latino/latina folks', 'young people',
       'black folks, non-whites', 'Democrats', 'liberals, Antifa',
       'pregnant folks', 'asian folks, latino/latina folks', 'mulattos',
       'people of color', 'Non-whites',
       'black folks, latino/latina folks, native american/first nation folks',
       'all non white races', 'feminist',
       'overweight/fat folks, ugly folks', 'asian folks, Indians'],
      dtype=object)

In [ ]:
from transformers import AutoTokenizer

t5_checkpoint = "google-t5/t5-small"
finetune_tokenizer = AutoTokenizer.from_pretrained(t5_checkpoint)

/usr/local/lib/python3.10/dist-packages/huggingface_hub/utils/_token.py:89: UserWarning:
The secret `HF_TOKEN` does not exist in your Colab secrets.
To authenticate with the Hugging Face Hub, create a token in your settings tab (https://huggingface.co/settings/tokens), set it as secret in your Google Colab and restart your session.
You will be able to reuse this secret in all of your notebooks.
Please note that authentication is recommended but still optional to access public models or datasets.
  warnings.warn(

tokenizer_config.json:   0%|          | 0.00/2.32k [00:00<?, ?B/s]

spiece.model:   0%|          | 0.00/792k [00:00<?, ?B/s]

tokenizer.json:   0%|          | 0.00/1.39M [00:00<?, ?B/s]

In [ ]:
task_prefix = "What is the implication of this hateful post:"
# task_mid1 = " with target minority "
# task_mid2 = " with target category "
task_mid3 = "\nLet's think about this step by step. "
final_answer_prompt = " Hence, the implication is: "
# post targetMinority targetCategory rationale
# targetStereotype

In [ ]:
class CustomDataset(Dataset):

  def __init__(self, data,tokenizer):
    # col names ['post','targetMinority','targetCategory','rationale','targetStereotype']
    self.posts = data['post'].tolist()
    self.minority = data['targetMinority'].tolist()
    self.category = data['targetCategory'].tolist()
    self.rationale = data['rationale'].tolist()
    self.label = data['targetStereotype'].tolist()
    self.tokenizer = tokenizer

  def __len__(self):
    return len(self.posts)

  def __getitem__(self, idx):
    inputs = task_prefix + str(self.posts[idx]) + "?" +task_mid3+ str(self.rationale[idx]) + final_answer_prompt
    targets = str(self.label[idx])
    input_enc = self.tokenizer(inputs, text_target=targets, max_length=512, padding=True ,truncation=True)

    # print(input_enc)
    return {
          'input_ids': input_enc['input_ids'],
          'attention_mask': input_enc['attention_mask'],
          'labels':input_enc['labels'],
          'input_text': inputs,
          'target_text': targets
          }

In [ ]:
# tokenized_dataset_train = train_dataset.map(preprocess_function, batched=True)
tokenized_dataset_train = CustomDataset(train_dataset,finetune_tokenizer)

In [ ]:
tokenized_dataset_train[500]

{'input_ids': [363,
  19,
  8,
  3,
  28722,
  13,
  48,
  5591,
  1329,
  442,
  10,
  5934,
  3320,
  63,
  425,
  226,
  102,
  52,
  3772,
  10,
  24500,
  3,
  63,
  32,
  720,
  524,
  114,
  10,
  2649,
  1303,
  17,
  5,
  509,
  87,
  1265,
  20611,
  15382,
  1298,
  102,
  7,
  210,
  58,
  1563,
  31,
  7,
  317,
  81,
  48,
  1147,
  57,
  1147,
  5,
  100,
  442,
  19,
  1702,
  5591,
  1329,
  250,
  34,
  2519,
  7,
  3,
  9,
  1817,
  32,
  122,
  63,
  29,
  3040,
  11,
  3735,
  8587,
  7525,
  1587,
  887,
  5,
  37,
  169,
  13,
  20,
  3822,
  6546,
  1612,
  13308,
  115,
  7059,
  8512,
  11,
  8,
  3735,
  2420,
  13,
  887,
  38,
  12143,
  4820,
  12,
  36,
  15319,
  28,
  3,
  9,
  824,
  7525,
  31324,
  6203,
  10947,
  7285,
  26524,
  7,
  11,
  2519,
  7,
  3,
  9,
  12068,
  903,
  13,
  3079,
  5,
  100,
  686,
  13,
  1612,
  11,
  7525,
  54,
  4139,
  12,
  3,
  9,
  1543,
  13,
  31973,
  11,
  4756,
  1587,
  887,
  5,
  5433,
  6,
  8,
  169,
  13,
  3,
  9,
  9674,
  3,
  15,
  51,
  21892,
  16,
  8,
  607,
  13,
  3,
  9,
  4740,
  856,
  15523,
  7,
  3,
  9,
  1254,
  13,
  28986,
  11,
  31973,
  1587,
  887,
  5,
  9126,
  6,
  48,
  442,
  2519,
  7,
  10947,
  11,
  5591,
  1329,
  18537,
  1587,
  887,
  11,
  19452,
  7,
  18488,
  7285,
  7982,
  7,
  5,
  3,
  13151,
  6,
  8,
  3,
  28722,
  19,
  10,
  1],
 'attention_mask': [1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1],
 'labels': [887, 33, 720, 2951, 1],
 'input_text': 'What is the implication of this hateful post:RT @yungxprnce: Approach yo bitch like: http://t.co/UHMIME9psw?\nLet\'s think about this step by step. This post is considered hateful because it promotes a misogynistic and objectifying attitude towards women. The use of derogatory language ("bitch") and the objectification of women as mere objects to be approached with a certain attitude perpetuates harmful gender stereotypes and promotes a toxic view of relationships. This type of language and attitude can contribute to a culture of disrespect and violence towards women. Additionally, the use of a violent emoji in the form of a gun further emphasizes a sense of aggression and disrespect towards women. Overall, this post promotes harmful and hateful attitudes towards women and reinforces damaging gender norms. Hence, the implication is: ',
 'target_text': 'women are bitches'}

In [ ]:
c = 0
for i in tokenized_dataset_train:
  print(i)
  print(len(i['input_ids']))
  if c>2:
    break
  c+=1
# just using to see length of input ids

{'input_ids': [363, 19, 8, 3, 28722, 13, 48, 5591, 1329, 442, 10, 5934, 3320, 23, 2703, 956, 32, 10, 3, 13076, 12417, 3, 89, 4636, 53, 3, 7315, 1304, 312, 22780, 29, 5, 148, 8882, 5341, 13721, 19126, 2293, 29, 63, 21622, 3, 89, 9, 122, 10779, 5, 58, 1563, 31, 7, 317, 81, 48, 1147, 57, 1147, 5, 100, 442, 19, 5591, 1329, 250, 34, 2284, 20, 3822, 6546, 1612, 11, 3, 7, 40, 3589, 12, 3211, 312, 22780, 29, 2549, 6, 3, 9, 8304, 1001, 17893, 5, 37, 169, 13, 1353, 224, 38, 96, 7315, 1304, 976, 96, 22498, 109, 2293, 29, 63, 976, 11, 96, 2157, 4397, 121, 33, 7447, 12130, 11, 20, 12450, 2610, 1587, 1001, 151, 5, 5433, 6, 8, 442, 92, 2284, 8, 1448, 96, 89, 9, 122, 10779, 121, 38, 46, 21548, 6, 31324, 1014, 13503, 27426, 5, 37, 1879, 5739, 13, 8, 442, 19, 8299, 11, 3353, 28, 11213, 6, 2924, 3, 9, 964, 8762, 12, 6263, 11, 36, 26192, 8, 568, 2799, 5, 100, 686, 13, 1612, 11, 13972, 13, 3, 9, 806, 1964, 11, 6949, 12602, 19, 29452, 11, 2519, 7, 5591, 11, 9192, 257, 5, 3, 13151, 6, 8, 3, 28722, 19, 10, 1], 'attention_mask': [1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1], 'labels': [66, 13721, 1], 'input_text': 'What is the implication of this hateful post:RT @iBeZo: Stupid fucking nigger LeBron. You flopping stupid jungle bunny monkey faggot.?\nLet\'s think about this step by step. This post is hateful because it uses derogatory language and slurs to attack LeBron James, a prominent black athlete. The use of terms such as "nigger," "jungle bunny," and "monkey" are deeply offensive and dehumanizing towards black people. Additionally, the post also uses the word "faggot" as an insult, perpetuating homophobia. The overall tone of the post is aggressive and filled with anger, showing a clear intention to harm and belittle the person mentioned. This type of language and targeting of a specific race and sexual orientation is unacceptable and promotes hate and discrimination. Hence, the implication is: ', 'target_text': 'all stupid'}
204
{'input_ids': [363, 19, 8, 3, 28722, 13, 48, 5591, 1329, 442, 10, 196, 174, 3, 9, 3202, 45, 21450, 27, 54, 31, 17, 3, 89, 4636, 28, 175, 1857, 1001, 720, 2951, 58, 1563, 31, 7, 317, 81, 48, 1147, 57, 1147, 5, 100, 442, 19, 5591, 1329, 250, 34, 8397, 3, 9, 964, 14387, 581, 96, 4883, 447, 1001, 720, 2951, 121, 11, 3735, 15821, 887, 45, 21450, 38, 6949, 4820, 5, 938, 338, 20, 3822, 6546, 1612, 11, 3, 5503, 887, 12, 70, 1964, 11, 684, 13, 5233, 6, 8, 442, 31324, 6203, 10947, 26524, 7, 11, 19452, 7, 3, 9, 15446, 13, 4784, 485, 5, 94, 92, 18841, 24, 8, 10836, 2441, 887, 38, 26139, 11, 24177, 179, 6, 1066, 145, 1742, 20, 3473, 53, 13, 1445, 11, 21377, 5, 9126, 6, 48, 442, 2519, 7, 9192, 257, 11, 19452, 7, 3, 9, 12068, 7525, 1587, 887, 11, 151, 13, 3, 9, 824, 1964, 5, 3, 13151, 6, 8, 3, 28722, 19, 10, 1], 'attention_mask': [1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1], 'labels': [1001, 887, 33, 1857, 1], 'input_text': 'What is the implication of this hateful post:I need a girl from Jamaica I can\'t fuck with these basic black bitches?\nLet\'s think about this step by step. This post is hateful because it displays a clear bias against "basic black bitches" and objectifies women from Jamaica as sexual objects. By using derogatory language and reducing women to their race and country of origin, the post perpetuates harmful stereotypes and reinforces a mindset of superiority. It also implies that the poster views women as disposable and interchangeable, rather than individuals deserving of respect and dignity. Overall, this post promotes discrimination and reinforces a toxic attitude towards women and people of a certain race. Hence, the implication is: ', 'target_text': 'black women are basic'}
166
{'input_ids': [363, 19, 8, 3, 28722, 13, 48, 5591, 1329, 442, 10, 329, 32, 6073, 143, 720, 2951, 6139, 58, 1563, 31, 7, 317, 81, 48, 1147, 57, 1147, 5, 100, 442, 2284, 20, 3822, 6546, 1612, 11, 2519, 7, 4756, 1587, 887, 57, 3, 13215, 12, 135, 38, 96, 2360, 2951, 121, 11, 15495, 24, 79, 33, 1153, 6737, 12, 11454, 655, 57, 3, 9, 568, 2650, 11019, 120, 5, 94, 31324, 6203, 10947, 7285, 26524, 7, 11, 8397, 3, 9, 2136, 13, 23950, 1587, 887, 5, 100, 773, 13, 1612, 11, 7525, 4139, 7, 12, 3, 9, 12068, 11, 24550, 1164, 21, 887, 5, 3, 13151, 6, 8, 3, 28722, 19, 10, 1], 'attention_mask': [1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1], 'labels': [887, 54, 31, 17, 2174, 4845, 1], 'input_text': 'What is the implication of this hateful post:Molly make bitches crazy?\nLet\'s think about this step by step. This post uses derogatory language and promotes violence towards women by referring to them as "bitches" and suggesting that they are easily driven to madness by a person named Molly. It perpetuates harmful gender stereotypes and displays a lack of empathy towards women. This kind of language and attitude contributes to a toxic and hostile environment for women. Hence, the implication is: ', 'target_text': "women can't handle drugs"}
114
{'input_ids': [363, 19, 8, 3, 28722, 13, 48, 5591, 1329, 442, 10, 196, 17, 31, 7, 6613, 116, 3, 76, 129, 3, 9, 1001, 3955, 11454, 79, 456, 6922, 3, 122, 88, 17, 235, 258, 3, 9, 720, 524, 58, 1563, 31, 7, 317, 81, 48, 1147, 57, 1147, 5, 100, 442, 19, 5591, 1329, 250, 34, 31324, 6203, 10947, 26524, 7, 81, 1001, 887, 5, 938, 338, 8, 1448, 96, 122, 88, 17, 235, 121, 11, 3874, 135, 3, 9, 96, 115, 7059, 976, 8, 2291, 19, 20, 12450, 2610, 11, 20, 3987, 53, 1001, 887, 6, 3, 5503, 135, 12, 2841, 11, 16687, 21888, 16843, 5, 100, 773, 13, 1612, 4139, 7, 12, 8, 358, 447, 22566, 23, 106, 11, 9192, 257, 7865, 57, 1001, 887, 6, 11, 34, 1267, 3, 9, 2136, 13, 23950, 11, 1705, 1587, 70, 2704, 5, 94, 92, 6490, 24, 34, 19, 9961, 12, 36, 26192, 11, 31973, 841, 3, 390, 30, 70, 1964, 11, 7285, 6, 84, 19, 59, 163, 4781, 1329, 68, 92, 2519, 7, 5591, 11, 9192, 257, 5, 3, 13151, 6, 8, 3, 28722, 19, 10, 1], 'attention_mask': [1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1], 'labels': [1001, 887, 33, 7623, 63, 5, 1], 'input_text': 'What is the implication of this hateful post:It\'s funny when u get a black female mad they start acting ghetto then a bitch?\nLet\'s think about this step by step. This post is hateful because it perpetuates harmful stereotypes about black women. By using the word "ghetto" and calling them a "bitch," the author is dehumanizing and degrading black women, reducing them to negative and stereotypical traits. This kind of language contributes to the systemic oppression and discrimination faced by black women, and it shows a lack of empathy and understanding towards their experiences. It also suggests that it is acceptable to belittle and disrespect someone based on their race and gender, which is not only hurtful but also promotes hate and discrimination. Hence, the implication is: ', 'target_text': 'black women are trashy.'}
187

In [ ]:
# tokenized_dataset_val = val_dataset.map(preprocess_function, batched=True)
tokenized_dataset_val = CustomDataset(val_dataset,finetune_tokenizer)

In [ ]:
from transformers import DataCollatorForSeq2Seq

data_collator = DataCollatorForSeq2Seq(tokenizer=finetune_tokenizer, model=t5_checkpoint)

In [ ]:
metric = load("sacrebleu")

Downloading builder script:   0%|          | 0.00/8.15k [00:00<?, ?B/s]

In [ ]:
from transformers import AutoModelForSeq2SeqLM, Seq2SeqTrainingArguments, Seq2SeqTrainer

finetune_model = AutoModelForSeq2SeqLM.from_pretrained(t5_checkpoint)

config.json:   0%|          | 0.00/1.21k [00:00<?, ?B/s]

model.safetensors:   0%|          | 0.00/242M [00:00<?, ?B/s]

generation_config.json:   0%|          | 0.00/147 [00:00<?, ?B/s]

In [ ]:
training_args = Seq2SeqTrainingArguments(
    output_dir="T5_cot_finetuned",
    evaluation_strategy="epoch",
    learning_rate=2e-5,
    per_device_train_batch_size=8,
    per_device_eval_batch_size=8,
    weight_decay=0.01,
    save_total_limit=3,
    num_train_epochs=30,
    predict_with_generate=True
)

trainer = Seq2SeqTrainer(
    model=finetune_model,
    args=training_args,
    train_dataset=tokenized_dataset_train,
    eval_dataset=tokenized_dataset_val,
    tokenizer=finetune_tokenizer,
    data_collator=data_collator,
)

In [ ]:
train_results = trainer.train()

In [ ]:
import pickle

model_path = "/content/drive/MyDrive/NLP_2024/Project/Generation/T5_COT_Generation.pkl"

with open(model_path, 'wb') as f:
    pickle.dump(finetune_model, f)

In [ ]:
# finetune_tokenizer.save_pretrained("")

In [ ]:
!pip install rouge-score

Collecting rouge-score
  Downloading rouge_score-0.1.2.tar.gz (17 kB)
  Preparing metadata (setup.py) ... done
Requirement already satisfied: absl-py in /usr/local/lib/python3.10/dist-packages (from rouge-score) (1.4.0)
Requirement already satisfied: nltk in /usr/local/lib/python3.10/dist-packages (from rouge-score) (3.8.1)
Requirement already satisfied: numpy in /usr/local/lib/python3.10/dist-packages (from rouge-score) (1.25.2)
Requirement already satisfied: six>=1.14.0 in /usr/local/lib/python3.10/dist-packages (from rouge-score) (1.16.0)
Requirement already satisfied: click in /usr/local/lib/python3.10/dist-packages (from nltk->rouge-score) (8.1.7)
Requirement already satisfied: joblib in /usr/local/lib/python3.10/dist-packages (from nltk->rouge-score) (1.4.0)
Requirement already satisfied: regex>=2021.8.3 in /usr/local/lib/python3.10/dist-packages (from nltk->rouge-score) (2023.12.25)
Requirement already satisfied: tqdm in /usr/local/lib/python3.10/dist-packages (from nltk->rouge-score) (4.66.2)
Building wheels for collected packages: rouge-score
  Building wheel for rouge-score (setup.py) ... done
  Created wheel for rouge-score: filename=rouge_score-0.1.2-py3-none-any.whl size=24933 sha256=5181586aa59a82f2b485247a290115e458ba3214945e5f16205cef535852b7d4
  Stored in directory: /root/.cache/pip/wheels/5f/dd/89/461065a73be61a532ff8599a28e9beef17985c9e9c31e541b4
Successfully built rouge-score
Installing collected packages: rouge-score
Successfully installed rouge-score-0.1.2

In [ ]:
DEVICE = torch.device('cuda' if torch.cuda.is_available() else 'cpu')

In [ ]:
# finetune_model = AutoModelForSeq2SeqLM.from_pretrained('finetuned_T5_final')

In [ ]:
# finetune_model.to(DEVICE)

In [ ]:
test_posts = test_dataset['post'].tolist()
test_minority = test_dataset['targetMinority'].tolist()
test_category = test_dataset['targetCategory'].tolist()
test_rationale = test_dataset['rationale'].tolist()
test_label = test_dataset['targetStereotype'].tolist()

In [ ]:
test_targets = []
test_generated = []
i = 0
for idx in range(len(test_posts)):
    inputs = task_prefix + str(test_posts[idx]) + "?" +task_mid3+ str(test_rationale[idx]) + final_answer_prompt
    input_ids = finetune_tokenizer.encode(inputs, return_tensors="pt").to(DEVICE)
    output = finetune_model.generate(input_ids, max_length=50, num_beams=4, early_stopping=True)
    output_text = finetune_tokenizer.decode(output[0], skip_special_tokens=True)
    test_generated.append(output_text)
    test_targets.append(test_label[idx])

In [ ]:
count = 20
i = 0
for j in range(len(test_generated)):
  print("Target:", test_targets[j])
  print("Generated:", test_generated[j])
  print("**********************************************")

Streaming output truncated to the last 5000 lines.
Generated: women are bitches
**********************************************
Target: gay men are indecisive
Generated: black people are faggots
**********************************************
Target: gay men are ugly
Generated: gay men are faggots
**********************************************
Target: women don't value the right things
Generated: women are hoes
**********************************************
Target: women are promiscuous
Generated: black people are hoes
**********************************************
Target: fat women are unattractive
Generated: black people are fat
**********************************************
Target: are all bitches
Generated: women are bitches
**********************************************
Target: act like children
Generated: mexicans are bitches
**********************************************
Target: women are hoes
Generated: black people are hoes
**********************************************
Target: woman are sex objects
Generated: black people are bitches
**********************************************
Target: women are attracted to money
Generated: women are bitches
**********************************************
Target: women are more likely to be into drugs.
Generated: women are bitches
**********************************************
Target: women are all the same
Generated: women are bitches
**********************************************
Target: mentally disabled folks are r*tarded
Generated: mentally disabled folks are retarded
**********************************************
Target: being gay is wrong
Generated: gay men are faggots
**********************************************
Target: women are bitches
Generated: women are bitches
**********************************************
Target: mentally disabled folks are r*tarded
Generated: mentally disabled folks are retards
**********************************************
Target: women sleep around
Generated: women are hoes
**********************************************
Target: women are gold diggers
Generated: women are hoes
**********************************************
Target: women are promiscuous
Generated: trivializes harm to victims
**********************************************
Target: women are hoes
Generated: women are hoes
**********************************************
Target: women are bitches
Generated: women are bitches
**********************************************
Target: should die
Generated: cancer patients are faggots
**********************************************
Target: fat people are unattractive.
Generated: fat people are bitches
**********************************************
Target: protect illegals
Generated: liberals are criminals
**********************************************
Target: liberals are annoying.
Generated: liberals are annoying
**********************************************
Target: black people are a lesser race
Generated: trivializes harm to victims
**********************************************
Target: retarded people are stupid
Generated: retarded people are stupid
**********************************************
Target: arabs are barbaric
Generated: muslims are pigs
**********************************************
Target: black people are ugly
Generated: ugly people are ugly
**********************************************
Target: derogatory term used
Generated: black people are inferior
**********************************************
Target: all latinos are immigrants
Generated: are bigots
**********************************************
Target: black people are niggers
Generated: women are niggers
**********************************************
Target: are sexually promiscous when drunk
Generated: women are bitches
**********************************************
Target: colombians are worthless
Generated: trivializes harm to victims
**********************************************
Target: christians take advantage of tax breaks
Generated: christians are hypocrites
**********************************************
Target: are all dumb
Generated: black people are criminals
**********************************************
Target: black folks are dirty
Generated: black people are niggas
**********************************************
Target: are niggers
Generated: black people are stupid
**********************************************
Target: black folks are angry
Generated: black people are bad
**********************************************
Target: women are bitches
Generated: black people are niggers
**********************************************
Target: is inherently bad
Generated: dominican folks ruin their lives
**********************************************
Target: woman are bitches/female dogs
Generated: trivializes harm to victims
**********************************************
Target: disabled people are worth name calling
Generated: mentally disabled folks aren't smart
**********************************************
Target: womens cheat
Generated: women are promiscuous
**********************************************
Target: retarded is an offensive term
Generated: mentally disabled folks are retards
**********************************************
Target: black people are dishonest
Generated: black people lie
**********************************************
Target: women are hoes
Generated: women are hoes
**********************************************
Target: conservatives blindly support their reps
Generated: muslims are terrorists
**********************************************
Target: women are childish
Generated: women are sex objects
**********************************************
Target: cops are racist
Generated: police speak to you
**********************************************
Target: labour party folks are liars
Generated: lib dems are weak
**********************************************
Target: trivializes harm to victims
Generated: trivializes harm to victims
**********************************************
Target: conservatives are perverts
Generated: trivializes harm to victims
**********************************************
Target: uk is undesirable
Generated: u.k. people are all bullied
**********************************************
Target: are hoes
Generated: women are hoes
**********************************************
Target: black people aren't as good as whites
Generated: black people are niggas
**********************************************
Target: women who enjoy sex are whores.
Generated: women are hoes
**********************************************
Target: women being assertive are bitchy
Generated: women are bitches
**********************************************
Target: black folks shouldn't be trusted
Generated: women are bitches
**********************************************
Target: blacks are stupid
Generated: black people are stupid
**********************************************
Target: niggas is a slang term
Generated: black people are niggers
**********************************************
Target: niggas is a slang term
Generated: black people are niggas
**********************************************
Target: black folks are disloyal
Generated: black people are niggers
**********************************************
Target: black men don't take care of their babies
Generated: black people are niggas
**********************************************
Target: are idiots
Generated: liberals are stupid
**********************************************
Target: uses the n word
Generated: black people are niggas
**********************************************
Target: soviets are criminals
Generated: trivializes harm to victims
**********************************************
Target: refers to women as bitches
Generated: women are bitches
**********************************************
Target: men only drink.
Generated: women are sex objects
**********************************************
Target: are failures
Generated: liberals are incompetent
**********************************************
Target: black folks are inferior
Generated: black people are ugly
**********************************************
Target: women act like they are superior
Generated: women are bitches
**********************************************
Target: conservatives are incompetent
Generated: liberals are nihilism
**********************************************
Target: women are bitches
Generated: women are bitches
**********************************************
Target: are loose
Generated: women are sex objects
**********************************************
Target: black folks are hateful
Generated: black people are niggas
**********************************************
Target: women change who they are to please men
Generated: black people are weird
**********************************************
Target: white people aren't superior
Generated: black people are crackers
**********************************************
Target: black people are worthless
Generated: black people are niggas
**********************************************
Target: women are vindictive
Generated: women are hypocrites
**********************************************
Target: trump supporters are stupid
Generated: liberals are terrorists
**********************************************
Target: russians are always doing something
Generated: trivializes harm to victims
**********************************************
Target: lesbian women are lustful
Generated: black people are niggers
**********************************************
Target: pagans are less than christians
Generated: christians are pedophiles
**********************************************
Target: women aren't equal to men
Generated: women are sex objects
**********************************************
Target: muslims immigrants are terrorists
Generated: muslims are terrorists
**********************************************
Target: are promiscous
Generated: women are hoes
**********************************************
Target: making our democracy less than
Generated: democrats deserve to be rewarded
**********************************************
Target: women are refereed to as a derogatory word
Generated: black people are niggers
**********************************************
Target: conservatives are spineless
Generated: conservatives refuse to stand up
**********************************************
Target: korean people would do anything to get what they want
Generated: muslims are terrorists
**********************************************
Target: mentally disabled folks are violent
Generated: physically disabled folks are useless
**********************************************
Target: makes light about holocaust
Generated: jewish people are dirty
**********************************************
Target: afghans practise beastiality
Generated: afghans are goats
**********************************************
Target: priests are pedophiles
Generated: mentally disabled folks are retarded
**********************************************
Target: jews should be burned
Generated: trivializes harm to victims
**********************************************
Target: black folks are like animals
Generated: black people are criminals
**********************************************
Target: black people are lynched.
Generated: black people are lynched
**********************************************
Target: implies black kids are fast
Generated: black people are criminals
**********************************************
Target: jewish people think genocide is funny
Generated: jewish people are burning
**********************************************
Target: black people are non listeners
Generated: blacks are slaves
**********************************************
Target: holocaust
Generated: trivializes harm to victims
**********************************************
Target: black folks are n-words
Generated: black people are niggers
**********************************************
Target: have slanted eyes
Generated: asian people always look the same
**********************************************
Target: native americans are inferior
Generated: native americans were slaves
**********************************************
Target: jewish people are executed
Generated: trivializes harm to victims
**********************************************
Target: unfair advantages
Generated: black folks are hard to be white
**********************************************
Target: christian religious leaders molest people
Generated: pastors are bad at slang
**********************************************
Target: jewish people are dumb.
Generated: trivializes harm to victims
**********************************************
Target: disabled people are a joke.
Generated: trivializes harm to victims
**********************************************
Target: thai women are actually men
Generated: thai folks are sex objects
**********************************************
Target: implies black teens are stupid
Generated: africans are poor
**********************************************
Target: women don't deserve equal rights
Generated: women deserve rights
**********************************************
Target: blacks are oversensitive about the n-word
Generated: black people are sluts
**********************************************
Target: jews are gay
Generated: holocaust joke
**********************************************
Target: jews were burned
Generated: jewish people deserved the holocaust
**********************************************
Target: jews deserved to be burned
Generated: trivializes harm to victims
**********************************************
Target: black people are irresponsible
Generated: black people don't care for their families
**********************************************
Target: transwomen are unpleasant
Generated: trans women are sex objects
**********************************************
Target: hitler killed a lot of jews
Generated: trivializes harm to victims
**********************************************
Target: jewish folks are frugal.
Generated: jewish people deserve to die
**********************************************
Target: women are irrational.
Generated: women are violent
**********************************************
Target: women are sex objects
Generated: trivializes harm to victims
**********************************************
Target: syrians are all violent.
Generated: syrians are terrorists
**********************************************
Target: indian folks are promiscuous
Generated: trivializes harm to victims
**********************************************
Target: calls women sluts
Generated: women are whoremones
**********************************************
Target: child sexual assault victims are objectified
Generated: trivializes harm to victims
**********************************************
Target: black folks are all criminals
Generated: black people are thieves
**********************************************
Target: ethiopians are starved
Generated: ethiopians are poor
**********************************************
Target: black people are dishonest.
Generated: racial slur
**********************************************
Target: jews lives aren't worth anything
Generated: trivializes harm to victims
**********************************************
Target: black people can't swim
Generated: blacks are the fastest runners
**********************************************
Target: bad at sports
Generated: black people are not good at sports
**********************************************
Target: black folks are less than human
Generated: black people deserve to die
**********************************************
Target: trivializes harm to victims
Generated: trivializes harm to victims
**********************************************
Target: jewish folks deserved to die in the holocaust
Generated: trivializes harm to victims
**********************************************
Target: women are sex objects
Generated: trivializes harm to victims
**********************************************
Target: smart
Generated: trivializes harm to victims
**********************************************
Target: ethiopens are similar to insects
Generated: ethiopians are terrorists
**********************************************
Target: are marginalized for a joke
Generated: trivializes harm to victims
**********************************************
Target: poor folks are incompetent
Generated: women aren't intelligent
**********************************************
Target: asians can't see
Generated: japanese folks are stupid
**********************************************
Target: are illegal immigrants
Generated: mexicans are worthless
**********************************************
Target: the mentally ill are crazy
Generated: mentally ill people are worthless
**********************************************
Target: black folks are animals
Generated: black people are criminals
**********************************************
Target: being black is a negative thing,
Generated: black people are inferior
**********************************************
Target: priests are pedophiles
Generated: priests abuse boys
**********************************************
Target: asian people look the same
Generated: asian folks are inferior
**********************************************
Target: jewish people are weak
Generated: trivializes harm to victims
**********************************************
Target: indians are dirty
Generated: trivializes harm to victims
**********************************************
Target: abuses boys
Generated: trivializes harm to victims
**********************************************
Target: minorities are accepted at harvard
Generated: trivializes harm to victims
**********************************************
Target: chinese folks eat dogs
Generated: chinese people eat dogs
**********************************************
Target: fat people are stupid.
Generated: mentally disabled folks are retarded
**********************************************
Target: jewish people were massacred
Generated: trivializes harm to victims
**********************************************
Target: muslim folks are terrorists
Generated: muslims are terrorists
**********************************************
Target: black people have aids
Generated: trivializes harm to victims
**********************************************
Target: cancer is funny.
Generated: trivializes harm to victims
**********************************************
Target: autistic people get bullied
Generated: autistic people are stupid
**********************************************
Target: arabs are terrorists
Generated: arabs are terrorists
**********************************************
Target: have sex with daughters
Generated: trivializes harm to victims
**********************************************
Target: folks with depression are violent
Generated: depression is a joke.
**********************************************
Target: jewish people were killed by hitler.
Generated: trivializes harm to victims
**********************************************
Target: are meant to be slaves
Generated: black people are slaves
**********************************************
Target: black folks loiter
Generated: black people are criminals
**********************************************
Target: trivializes harm to victims
Generated: trivializes harm to victims
**********************************************
Target: women deserve to be hit
Generated: women are sex objects
**********************************************
Target: jews deserve to be gassed.
Generated: trivializes harm to victims
**********************************************
Target: don't deserve rights
Generated: trivializes harm to victims
**********************************************
Target: are worthless
Generated: paraplegics are sex objects
**********************************************
Target: mentally disabled are dumb
Generated: mentally disabled folks are retards
**********************************************

In [ ]:
!pip install rouge-score

Requirement already satisfied: rouge-score in /usr/local/lib/python3.10/dist-packages (0.1.2)
Requirement already satisfied: absl-py in /usr/local/lib/python3.10/dist-packages (from rouge-score) (1.4.0)
Requirement already satisfied: nltk in /usr/local/lib/python3.10/dist-packages (from rouge-score) (3.8.1)
Requirement already satisfied: numpy in /usr/local/lib/python3.10/dist-packages (from rouge-score) (1.25.2)
Requirement already satisfied: six>=1.14.0 in /usr/local/lib/python3.10/dist-packages (from rouge-score) (1.16.0)
Requirement already satisfied: click in /usr/local/lib/python3.10/dist-packages (from nltk->rouge-score) (8.1.7)
Requirement already satisfied: joblib in /usr/local/lib/python3.10/dist-packages (from nltk->rouge-score) (1.4.0)
Requirement already satisfied: regex>=2021.8.3 in /usr/local/lib/python3.10/dist-packages (from nltk->rouge-score) (2023.12.25)
Requirement already satisfied: tqdm in /usr/local/lib/python3.10/dist-packages (from nltk->rouge-score) (4.66.2)

In [ ]:
import evaluate
rouge = evaluate.load('rouge')
results = rouge.compute(predictions=test_generated, references=test_targets)
print(results)

Downloading builder script:   0%|          | 0.00/6.27k [00:00<?, ?B/s]

{'rouge1': 0.31308437118437105, 'rouge2': 0.16985774225774225, 'rougeL': 0.3109927154544804, 'rougeLsum': 0.3113439982986203}

In [ ]:
from datasets import load_metric
metric = load_metric("rouge")
results = metric.compute(predictions=test_generated, references=test_targets)
# print(results)
result = list(results.items())
for index in range(len(result)-1):
  type_, scores = result[index]
  precision = scores.mid.precision
  recall = scores.mid.recall
  f1 = scores.mid.fmeasure
  print(str(type_)+" with precision "+str(precision)+" with recall "+str(recall)+" and F1 score "+str(f1))

<ipython-input-36-4a703b08e2ee>:2: FutureWarning: load_metric is deprecated and will be removed in the next major version of datasets. Use 'evaluate.load' instead, from the new library 🤗 Evaluate: https://huggingface.co/docs/evaluate
  metric = load_metric("rouge")
/usr/local/lib/python3.10/dist-packages/datasets/load.py:759: FutureWarning: The repository for rouge contains custom code which must be executed to correctly load the metric. You can inspect the repository content at https://raw.githubusercontent.com/huggingface/datasets/2.19.0/metrics/rouge/rouge.py
You can avoid this message in future by passing the argument `trust_remote_code=True`.
Passing `trust_remote_code=True` will be mandatory to load this metric from the next major release of `datasets`.
  warnings.warn(

Downloading builder script:   0%|          | 0.00/2.17k [00:00<?, ?B/s]

rouge1 with precision 0.3300020408163262 with recall 0.31107646391890054 and F1 score 0.31308437118437105
rouge2 with precision 0.17613027210884355 with recall 0.17084206349206327 and F1 score 0.16985774225774225
rougeL with precision 0.32769489795918316 with recall 0.30911819678920494 and F1 score 0.3109927154544804

In [ ]:
from bert_score import score as bert_score
Ptestft, Rtestft, F1testft = bert_score(cands=test_generated, refs=test_targets, lang='en', verbose=True)
print("BERTScore Precision:", Ptestft.mean().item())
print("BERTScore Recall:", Rtestft.mean().item())
print("BERTScore F1:", F1testft.mean().item())

tokenizer_config.json:   0%|          | 0.00/25.0 [00:00<?, ?B/s]

config.json:   0%|          | 0.00/482 [00:00<?, ?B/s]

vocab.json:   0%|          | 0.00/899k [00:00<?, ?B/s]

merges.txt:   0%|          | 0.00/456k [00:00<?, ?B/s]

tokenizer.json:   0%|          | 0.00/1.36M [00:00<?, ?B/s]

model.safetensors:   0%|          | 0.00/1.42G [00:00<?, ?B/s]

Some weights of RobertaModel were not initialized from the model checkpoint at roberta-large and are newly initialized: ['roberta.pooler.dense.bias', 'roberta.pooler.dense.weight']
You should probably TRAIN this model on a down-stream task to be able to use it for predictions and inference.

calculating scores...
computing bert embedding.

  0%|          | 0/30 [00:00<?, ?it/s]

computing greedy matching.

  0%|          | 0/28 [00:00<?, ?it/s]

done in 4.80 seconds, 364.52 sentences/sec
BERTScore Precision: 0.8898860216140747
BERTScore Recall: 0.8925727605819702
BERTScore F1: 0.8910824656486511

In [ ]:
import nltk
from nltk.translate.bleu_score import corpus_bleu

# Example target and generated sentences
# target_sentences = ['The cat is on the mat', 'There is a dog', 'The sky is blue']
# generated_sentences = ['The cat is sitting on the mat', 'A dog is here', 'The sky is blue']

# Tokenize sentences
target_sentences_tokenized = [sentence.split() for sentence in test_targets]
generated_sentences_tokenized = [sentence.split() for sentence in test_generated]

# Calculate BLEU score
bleu_score = corpus_bleu([[ref] for ref in target_sentences_tokenized], generated_sentences_tokenized)

print("BLEU Score:", bleu_score)

BLEU Score: 0.1018801502678393